# shellcheck shell=bash
#
# The operator identity: the age key that edits the fleet's secrets, held in
# the Mac's Secure Enclave, and its registration in the audience file (ADR
# 0008 step 3).
#
# Sourced by bin/atyrode; every @substitution@ lives in that entry point.

# The operator is two recipients in .sops.yaml and this module handles one of
# them. `alex` is the daily identity: generated by age-plugin-se inside the
# Secure Enclave of the one registered Mac, unlocked by Touch ID for every
# edit, and by construction impossible to copy off the machine -- the file
# it writes is a handle the enclave understands, not key material. `alex-
# recovery` is the software key whose only copy is the break-glass note in
# Bitwarden; it is a recipient of every file so that a lost Mac costs one
# `sops updatekeys` and nothing more, and nothing here ever reads it.
#
# The key lands in the file sops reads by default, which is why the machine
# identity deliberately lives elsewhere (identity.sh): an activation must
# never be able to decrypt as the operator.
readonly operator_anchor=alex
readonly operator_recovery_anchor=alex-recovery

operator_key_file() {
  printf '%s/sops/age/keys.txt\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

# The enclave is the Mac's, so the ceremony is applicable on exactly the
# registered Darwin host and nowhere else. The registry decides, not uname:
# a Linux box asked with ATYRODE_HOST naming the Mac is a check exercising
# the ceremony, not a machine that grew an enclave.
operator_applicable() { # host-json
  [[ "$(jq -r '.system' <<<"$1")" == *-darwin ]]
}

# The public half is the `# public key:` line age-plugin-se writes above the
# identity line. It is read rather than derived because no program here may
# be handed the file that could echo the identity back: `age-keygen -y`
# rejects plugin identities outright, and `age-plugin-se recipients` would
# take the whole file on stdin. Silent, and never the identity line.
operator_recipient() {
  local key recipient
  key="$(operator_key_file)"
  [[ -r "$key" ]] || return 1
  recipient="$(sed -n 's/^# public key: //p' "$key" | head -n 1)"
  [[ "$recipient" =~ ^age1se1[0-9a-z]+$ ]] || return 1
  printf '%s\n' "$recipient"
}

# Why there is no usable operator identity, said the same way by show, init
# and the doctor probe. A file that exists without a Secure Enclave recipient
# is the day-zero Mac: the software key still on disk, which now belongs in
# the Bitwarden note alone. It is never overwritten and never read past its
# comment lines; the operator moves it aside.
operator_absence() {
  local key
  key="$(operator_key_file)"
  if [[ -e "$key" ]]; then
    printf '%s\n' "$key holds no Secure Enclave recipient; a software key there is the recovery identity, which belongs in Bitwarden alone, so move the file aside and then run: atyrode operator init"
  else
    printf '%s\n' "no operator identity yet at $key, so nothing under secrets/ can be edited here; create one with: atyrode operator init"
  fi
}

operator_registration_line() { # recipient
  printf -- '- &%s %s\n' "$operator_anchor" "$1"
}

# Registered means exactly that line, uncommented, in the packaged audience
# file: the slot is a comment until the ceremony fills it.
operator_registered() { # recipient
  grep -Eq "^[[:space:]]*-[[:space:]]*&$operator_anchor[[:space:]]+$1[[:space:]]*$" "$sops_audience"
}

# What the operator does next, said the same way by show, init and the doctor
# probe. The updatekeys step is phrased for the day it applies: nothing under
# secrets/ exists yet, and a file created after the slot is filled is
# encrypted to it from the start.
operator_say_registration() { # recipient
  say "add this line to .sops.yaml under keys, uncomment *$operator_anchor in every creation rule, then re-encrypt any file that already exists:"
  printf '  %s\n' "$(operator_registration_line "$1")" >&2
  printf '  %s\n' "$(paint 2 '$ sops updatekeys secrets/*.yaml')" >&2
  say "&$operator_recovery_anchor stays: it is the break-glass recipient of every file, and the only copy of its private half is the Bitwarden note"
}

# The key is generated by age-plugin-se, which creates the file at mode 0600
# itself and prints only the public half, on stdout; the modes are then
# asserted rather than trusted. The plugin asks the Secure Enclave for a new
# key under the given access control, which is what makes macOS prompt for
# Touch ID (or the login passcode) once here and on every later decryption.
operator_generate() { # key
  local key="$1" directory="${1%/*}"
  mkdir -p "$directory"
  chmod 700 "$directory"
  say "macOS will prompt for Touch ID: the key is minted inside the Secure Enclave and never leaves it"
  (umask 077 && infra_exec visible ATYRODE_AGE_PLUGIN_SE age-plugin-se keygen \
    --access-control=any-biometry-or-passcode -o "$key") ||
    die "$EX_SOFTWARE" "age-plugin-se did not write $key"
  chmod 600 "$key"
  say "wrote $key (mode 0600, directory mode 0700)"
}

# The doctor probe. Off the Mac there is nothing to have; on it, three states
# and one next step each: no key means the ceremony, a key the audience file
# does not name means the line to add, and a registered key means the
# operator can edit here.
probe_operator_identity() {
  local data recipient
  data="$(host_json "$(resolve_host)")"
  if ! operator_applicable "$data"; then
    provisioning_check_add operator-identity not-applicable platform-not-darwin \
      "the operator identity lives in the Secure Enclave of the registered Mac; this host cannot hold it" ""
    return 0
  fi
  if ! recipient="$(operator_recipient)"; then
    provisioning_unconfigured operator-identity "$(operator_absence)"
    return 0
  fi
  if ! operator_registered "$recipient"; then
    provisioning_check_add operator-identity degraded not-registered \
      "the operator recipient is not in .sops.yaml, so no secret is encrypted to it" \
      "add '$(operator_registration_line "$recipient")' to .sops.yaml under keys, uncomment *$operator_anchor in every creation rule, then run sops updatekeys on any existing file"
    return 0
  fi
  provisioning_check_add operator-identity ok "" \
    "registered in .sops.yaml as &$operator_anchor" ""
}

cmd_operator() {
  local action="" data host key recipient
  while [[ $# -gt 0 ]]; do
    case "$1" in
      show | init)
        [[ -z "$action" ]] || die "$EX_USAGE" "operator accepts one of show or init"
        action="$1"
        ;;
      *) die "$EX_USAGE" "unknown operator option: $1" ;;
    esac
    shift
  done
  [[ -n "$action" ]] || die "$EX_USAGE" "operator expects show or init"
  host="$(resolve_host)"
  data="$(host_json "$host")"
  operator_applicable "$data" ||
    die "$EX_DATAERR" "the operator identity lives in the Secure Enclave of the registered Mac, and $host is not it"
  key="$(operator_key_file)"

  if [[ "$action" == show ]]; then
    if ! recipient="$(operator_recipient)"; then
      say "$(operator_absence)"
      return "$EX_UNAVAILABLE"
    fi
    printf '%s\n' "$recipient"
    if operator_registered "$recipient"; then
      say "registered in .sops.yaml as &$operator_anchor"
    else
      operator_say_registration "$recipient"
    fi
    return 0
  fi

  # init is idempotent: a second run never replaces a key that files may
  # already be encrypted to and that the enclave could not give back, it
  # repeats the registration the operator still owes.
  if [[ -e "$key" ]]; then
    say "$key already exists; keeping it"
    recipient="$(operator_recipient)" || die "$EX_DATAERR" "$(operator_absence)"
  else
    operator_generate "$key"
    recipient="$(operator_recipient)" ||
      die "$EX_SOFTWARE" "the key at $key did not yield a Secure Enclave recipient"
  fi
  if operator_registered "$recipient"; then
    say "recipient $recipient is registered in .sops.yaml as &$operator_anchor"
  else
    operator_say_registration "$recipient"
  fi
}
