name: Update README.md

on:
  push:
    paths:
      - 'dotfiles/firefox/profile/user.js'
      - '.github/workflows/update-firefox-readme.yml'
      - 'dotfiles/firefox/readme_updater.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.x'

      - name: Update README.md
        run: python dotfiles/firefox/readme_updater.py

      - name: Commit changes
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add dotfiles/firefox/README.md
            git commit -m 'Update README.md via GitHub Action' || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}