// code — the prompt→profile generator, as a Bubble Tea TUI.
//
// Manifest (generated by omp-configured, so this binary stays generic):
//
//	CODE_GENERATED     : generated.plain (facet-grid blocks, keyed by combo id)
//	CODE_USAGE         : optional command (space-split) that prints `omp usage --json`
//	CODE_SELECTION_STATE: optional persisted generator facet choices; empty disables it
//	CODE_AUTH_VAULTS   : optional JSON override for the machine-local vault manifest
//	CODE_AUTH_VAULTS_FILE: optional path override for the XDG-local vault manifest
//	CODE_AUTH_STATE    : persisted {selected,disabled} vault state (0600, mutable)
//	CODE_OMP           : the omp-managed executable — launches every trusted session
//	                     on the shared `default` client profile with the selected
//	                     vault's broker env: a generated profile as a one-shot
//	                     --config, or the managed defaults when nothing was generated
//	CODE_OMP_RAW       : plain omp, used for the per-vault login handoff
//	CODE_OMP_UNTRUSTED : the ompu sandbox executable — launched by the u key
package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"

	clikit "cli-kit"
	"github.com/charmbracelet/bubbles/help"
	"github.com/charmbracelet/bubbles/key"
	"github.com/charmbracelet/bubbles/spinner"
	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// ── keybindings (drive both input handling and the bubbles/help footer) ───────
type keyMap struct {
	Move, Change, Reset, Depth, Refresh, Auth, Manager, Collapse, Usage, Launch, Managed, Untrusted, Help, Quit key.Binding
}

// ShortHelp is a static single-line stand-in used only when measuring the
// footer height for mode selection (which would otherwise recurse through the
// state-derived compact help). The rendered compact line comes from
// contextHelp, which derives its bindings from the live model state (#198).
func (k keyMap) ShortHelp() []key.Binding {
	return []key.Binding{k.Move, k.Change, k.Reset, k.Help, k.Quit}
}
func (k keyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{k.Move, k.Change, k.Reset},
		{k.Depth, k.Refresh, k.Auth, k.Manager, k.Collapse, k.Usage},
		{k.Launch, k.Managed, k.Untrusted, k.Help, k.Quit},
	}
}

var keys = keyMap{
	Move:      key.NewBinding(key.WithKeys("up", "down", "j", "k"), key.WithHelp("↑↓", "move")),
	Change:    key.NewBinding(key.WithKeys("left", "right", "h", "l"), key.WithHelp("←→", "change")),
	Reset:     key.NewBinding(key.WithKeys("d"), key.WithHelp("d", gReset+" defaults")),
	Depth:     key.NewBinding(key.WithKeys("f"), key.WithHelp("f", "primary ⇄ full chains")),
	Refresh:   key.NewBinding(key.WithKeys("r"), key.WithHelp("r", "refresh usage")),
	Auth:      key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "switch vault")),
	Manager:   key.NewBinding(key.WithKeys("v"), key.WithHelp("v", "manage vaults")),
	Collapse:  key.NewBinding(key.WithKeys("p"), key.WithHelp("p", "show/hide routing")),
	Usage:     key.NewBinding(key.WithKeys("s"), key.WithHelp("s", "show/hide usage")),
	Launch:    key.NewBinding(key.WithKeys("enter"), key.WithHelp("⏎", "launch")),
	Managed:   key.NewBinding(key.WithKeys("m"), key.WithHelp("m", "managed omp")),
	Untrusted: key.NewBinding(key.WithKeys("u"), key.WithHelp("u", "sandbox")),
	Help:      key.NewBinding(key.WithKeys("?"), key.WithHelp("?", "more")),
	Quit:      key.NewBinding(key.WithKeys("q", "esc", "ctrl+c"), key.WithHelp("q", "quit")),
}

// defaultSel returns a fresh copy of the generator's default facet selection —
// used both to seed the model and to restore it via the reset key.
func defaultSel() map[string]string {
	return map[string]string{"lane": "mixed", "model": "smart", "thinking": "medium", "advisor": "glance", "spark": "on", "fable": "off", "main": "off", "fast": "off"}
}

// ── palette ──────────────────────────────────────────────────────────────────
// The palette, glyphs, and styles now live in the shared cli-kit; these are
// ergonomic local aliases so the rest of the file reads unchanged. cli-kit is
// the single source both `code` and `atyrode` build on.
const (
	cAcc   = clikit.CAcc
	cBord  = clikit.CBord
	cHead  = clikit.CHead
	cSelBg = clikit.CSelBg
	cGreen = clikit.CGreen
)

const (
	gWarn  = clikit.GWarn
	gReset = clikit.GReset
)

var (
	meterRamp = clikit.MeterRamp

	stDim    = clikit.StDim
	stHead   = clikit.StHead
	stWarn   = clikit.StWarn
	stBrk    = clikit.StBrk
	stStruck = clikit.StStruck

	// stKey renders an inline key cue (r, a, s, p) — visually secondary but
	// readable against the background, per the section-chrome convention.
	stKey = lipgloss.NewStyle().Foreground(lipgloss.Color(cHead))

	// Title-local hotkey cues (d · defaults, p · hide, s · hide) are quieter
	// than the footer help: terminals have no portable alpha, so these are
	// dedicated pre-blended tokens — CHead/CDim mixed ~40% toward the app's
	// dark backdrop — applied to the whole cue, key included. Pre-blending is
	// used instead of ANSI faint because faint's dimming factor varies wildly
	// across terminals (and would double-dim already-muted text). Footer
	// recovery cues keep the brighter help styles for readability.
	stCueKey = lipgloss.NewStyle().Foreground(lipgloss.Color("#646b76")) // CHead → backdrop
	stCue    = lipgloss.NewStyle().Foreground(lipgloss.Color("#4f5768")) // CDim → backdrop

	// layout + meter primitives now live in cli-kit
	padLeft    = clikit.PadLeft
	pad        = clikit.Pad
	windowList = clikit.WindowList

	modelRe = regexp.MustCompile(`(gpt|claude)[A-Za-z0-9._-]*:(minimal|low|medium|high|xhigh|max)`)
)

// ── colourisers ──────────────────────────────────────────────────────────────
func lvl(s string) int {
	switch s {
	case "minimal":
		return 0
	case "low":
		return 1
	case "medium":
		return 2
	case "high":
		return 3
	case "xhigh":
		return 4
	}
	return 5
}

func shortModel(name string) string {
	if name == "gpt-5.4" {
		return name
	}
	p := strings.Split(name, "-")
	if strings.HasPrefix(name, "claude") && len(p) > 1 {
		return p[1]
	}
	return p[len(p)-1]
}

func clampByte(x float64) int {
	v := int(x)
	if v > 255 {
		return 255
	}
	if v < 0 {
		return 0
	}
	return v
}

func paintModel(tok string) string {
	i := strings.LastIndex(tok, ":")
	name, level := tok[:i], tok[i+1:]
	var br, bg, bb float64
	if strings.HasPrefix(tok, "gpt") {
		br, bg, bb = 110, 170, 240
	} else {
		br, bg, bb = 240, 160, 105
	}
	f := 0.60 + float64(lvl(level))*0.088
	col := lipgloss.Color(fmt.Sprintf("#%02x%02x%02x", clampByte(br*f), clampByte(bg*f), clampByte(bb*f)))
	return lipgloss.NewStyle().Foreground(col).Render(shortModel(name) + ":" + level)
}

func colorizeRoute(line string) string { return modelRe.ReplaceAllStringFunc(line, paintModel) }

// providerOf maps a short/long model name to its quota bucket.
func bucketOf(model string) string {
	m := model
	if i := strings.IndexByte(m, ':'); i >= 0 {
		m = m[:i]
	}
	switch {
	case strings.Contains(m, "fable"):
		return "claude-fable"
	case strings.Contains(m, "spark"):
		return "codex-spark"
	case strings.Contains(m, "claude"), strings.Contains(m, "sonnet"),
		strings.Contains(m, "haiku"), strings.Contains(m, "opus"):
		return "claude-main"
	}
	return "codex-main"
}

// ── data ─────────────────────────────────────────────────────────────────────
// loadBlocks parses a generated page into name -> role rows.
func loadBlocks(path string) map[string][]string {
	blocks := map[string][]string{}
	f, err := os.Open(path)
	if err != nil {
		return blocks
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1024*128), 1024*128)
	var cur string
	for sc.Scan() {
		line := sc.Text()
		if line == "" {
			cur = ""
			continue
		}
		if line[0] != ' ' {
			if fs := strings.Fields(line); len(fs) > 0 {
				cur = fs[0]
				blocks[cur] = nil
			}
			continue
		}
		if cur != "" {
			blocks[cur] = append(blocks[cur], line)
		}
	}
	return blocks
}

// ── usage + availability ─────────────────────────────────────────────────────
type usageWin struct {
	label    string
	pct      int
	tier     string
	secs     int64 // seconds until reset (relative)
	dur      int64 // window length in seconds
	prov     string
	stale    bool  // retained from the last successful fetch after a refresh omitted this window
	missing  bool  // never observed: rendered as a deterministic placeholder row
	observed int64 // Unix timestamp of the last real value; retained across cache fallback
}

// resetCredits tracks OpenAI reset credits: how many are currently available
// and the seconds until each available credit expires (relative, unsorted).
type resetCredits struct {
	avail int
	exp   []int64
}

type availability struct {
	bucket        map[string]string // bucket -> "ok" | "maxed" | "unauthed"
	reset         map[string]int64
	wins          []usageWin
	credits       resetCredits
	ok            bool
	accounts      map[string][]vaultAccount
	accountsOK    bool
	accountsStale bool
}

// loadAvailability fetches identity and usage for one vault. Managed broker
// vaults read the broker's redacted snapshot and aggregate usage endpoints
// directly, avoiding client-side credential-schema failures in unrelated
// providers. Standalone configurations retain the forwarded CLI fallback.
// Every path is read-only.
func loadAvailability(cmd string, v vault) availability {
	a := availability{
		bucket: map[string]string{}, reset: map[string]int64{},
		accounts: map[string][]vaultAccount{},
	}
	if accounts, err := loadVaultAccounts(v); err == nil {
		a.accounts, a.accountsOK = accounts, true
	}
	if cmd == "" {
		return a
	}

	var out []byte
	var err error
	if v.BrokerURL != "" && v.TokenFile != "" {
		out, err = fetchVaultEndpoint(v, "/v1/usage")
	} else {
		env, envErr := brokerEnv(v)
		if envErr != nil {
			return a
		}
		parts := strings.Fields(cmd)
		args := withOMPProfile("default", parts[1:]...)
		c := exec.Command(parts[0], args...)
		c.Env = withBrokerEnv(os.Environ(), env)
		out, err = c.Output()
	}
	if err != nil || len(out) == 0 {
		return a
	}
	var doc struct {
		Reports []struct {
			Provider string `json:"provider"`
			Limits   []struct {
				Label string `json:"label"`
				Scope struct {
					Tier string `json:"tier"`
				} `json:"scope"`
				Amount struct {
					UsedFraction float64 `json:"usedFraction"`
				} `json:"amount"`
				Window struct {
					ResetsAt   int64 `json:"resetsAt"`
					DurationMs int64 `json:"durationMs"`
				} `json:"window"`
			} `json:"limits"`
			ResetCredits struct {
				AvailableCount int `json:"availableCount"`
				Credits        []struct {
					ExpiresAt string `json:"expiresAt"`
					Status    string `json:"status"`
				} `json:"credits"`
			} `json:"resetCredits"`
		} `json:"reports"`
	}
	if json.Unmarshal(out, &doc) != nil {
		return a
	}
	a.ok = true
	provSeen := map[string]bool{}
	now := time.Now().Unix()
	for _, r := range doc.Reports {
		provSeen[r.Provider] = true
		for _, l := range r.Limits {
			pct := int(l.Amount.UsedFraction*100 + 0.5)
			a.wins = append(a.wins, usageWin{label: l.Label, pct: pct, tier: l.Scope.Tier,
				secs: l.Window.ResetsAt/1000 - now, dur: l.Window.DurationMs / 1000,
				prov: r.Provider, observed: now})
			bkt := bucketForProviderTier(r.Provider, l.Scope.Tier)
			if bkt == "" {
				continue
			}
			if pct >= 100 {
				a.bucket[bkt] = "maxed"
				a.reset[bkt] = l.Window.ResetsAt/1000 - now
			} else if a.bucket[bkt] != "maxed" {
				a.bucket[bkt] = "ok"
			}
		}
		if r.Provider == "openai-codex" {
			a.credits.avail = r.ResetCredits.AvailableCount
			for _, c := range r.ResetCredits.Credits {
				if c.Status != "available" {
					continue
				}
				if t, err := time.Parse(time.RFC3339, c.ExpiresAt); err == nil {
					a.credits.exp = append(a.credits.exp, t.Unix()-now)
				}
			}
		}
	}
	for _, b := range []string{"codex-main", "codex-spark", "claude-main", "claude-fable"} {
		p := "openai-codex"
		if strings.HasPrefix(b, "claude") {
			p = "anthropic"
		}
		if !provSeen[p] {
			a.bucket[b] = "unauthed"
		} else if _, ok := a.bucket[b]; !ok {
			a.bucket[b] = "ok"
		}
	}
	return a
}

func bucketForProviderTier(prov, tier string) string {
	if prov == "openai-codex" {
		if tier == "spark" {
			return "codex-spark"
		}
		if tier == "" || tier == "-" {
			return "codex-main"
		}
	}
	if prov == "anthropic" {
		if tier == "fable" {
			return "claude-fable"
		}
		if tier == "" || tier == "-" {
			return "claude-main"
		}
	}
	return ""
}

func (a availability) down(bucket string) bool {
	return a.bucket[bucket] == "maxed" || a.bucket[bucket] == "unauthed"
}

// reconcileUsage folds a freshly fetched availability over the one currently
// shown, so a flaky upstream never wipes known-good data. It returns the
// availability to display plus whether the whole panel is stale:
//
//   - a total fetch failure after any prior success keeps the previous
//     availability wholesale and reports it stale — the control row shows a
//     refresh-failed warning instead of dropping to the unauthenticated error;
//   - a successful payload that omits the Anthropic fable window (the
//     "Claude 7 Day (Fable)" datum is flaky upstream) retains the last
//     observed fable row marked stale, along with its bucket/reset state, so
//     down-routing stays conservative instead of silently flipping a maxed
//     fable back to ok on missing evidence;
//   - a successful payload with no fable window ever observed appends a
//     deterministic unavailable placeholder, so the datum appearing on a
//     later refresh never pops the panel geometry.
//
// Fresh values always win; nothing is fabricated — retained rows are visibly
// marked stale and placeholders carry no numbers.
func reconcileUsage(prev, next availability) (availability, bool) {
	if !next.accountsOK && prev.accountsOK {
		next.accounts, next.accountsOK, next.accountsStale = prev.accounts, true, true
	}
	if !next.ok {
		if prev.ok {
			prev.accounts, prev.accountsOK, prev.accountsStale =
				next.accounts, next.accountsOK, next.accountsStale
			return prev, true
		}
		return next, false
	}
	hasClaude, hasFable := false, false
	for _, w := range next.wins {
		if w.prov != "anthropic" {
			continue
		}
		hasClaude = true
		if w.tier == "fable" {
			hasFable = true
		}
	}
	if !hasClaude || hasFable {
		return next, false
	}
	for _, w := range prev.wins {
		if w.prov == "anthropic" && w.tier == "fable" && !w.missing {
			w.stale = true
			next.wins = append(next.wins, w)
			// Carry the bucket/reset state observed with the retained window:
			// loadAvailability defaults an unseen bucket to "ok", which would
			// route onto a fable the last real datum said was maxed.
			if st, ok := prev.bucket["claude-fable"]; ok {
				next.bucket["claude-fable"] = st
			}
			if r, ok := prev.reset["claude-fable"]; ok {
				next.reset["claude-fable"] = r
			}
			return next, false
		}
	}
	next.wins = append(next.wins, fablePlaceholder)
	return next, false
}

// fablePlaceholder is the never-observed fable window's deterministic
// stand-in: the real payload label (so shortWin renders the same "7d fable"
// tag) and window length, with no usage numbers to fabricate.
var fablePlaceholder = usageWin{label: "Claude 7 Day (Fable)", tier: "fable", dur: 7 * 24 * 3600, prov: "anthropic", missing: true}

// ── routing render (depth: 0 lead · 1 full) ──────────────────────────────────
// renderRoute lays out each role's chain, wrapping cleanly at `width`: when a
// chain doesn't fit, it breaks after an arrow and the continuation is indented
// to align under the first model, so it reads as one hanging block rather than a
// ragged wrap. Down (maxed/unauthed) models are struck through.
func renderRoute(rows []string, depth int, a availability, width int) string {
	if width < 24 {
		width = 24
	}
	arrow := stDim.Render(" → ")
	var out []string
	for _, r := range rows {
		locs := modelRe.FindAllStringIndex(r, -1)
		if len(locs) == 0 { // a note/meta line with no models — pass through
			out = append(out, colorizeRoute(r))
			continue
		}
		label := r[:locs[0][0]] // role + its alignment padding, kept verbatim
		labelW := lipgloss.Width(label)
		indent := strings.Repeat(" ", labelW)

		type tok struct {
			text string
			down bool
		}
		var toks []tok
		for _, loc := range locs {
			mt := r[loc[0]:loc[1]]
			toks = append(toks, tok{mt, a.ok && a.down(bucketOf(mt))})
		}
		// how many to show: full → all; lead → primary, or up to the first live
		// model when the lead is down (the one that actually runs).
		last := len(toks) - 1
		if depth == 0 {
			last = 0
			for i, t := range toks {
				last = i
				if !t.down {
					break
				}
			}
		}
		// render a token as it displays (short name), returning the styled
		// string and its display width — struck if the model is down.
		render := func(t tok) (string, int) {
			c := strings.LastIndexByte(t.text, ':')
			short := shortModel(t.text[:c]) + t.text[c:]
			if t.down {
				s := stStruck.Render(short)
				return s, lipgloss.Width(s)
			}
			s := colorizeRoute(t.text) // paintModel shortens + colours
			return s, lipgloss.Width(s)
		}
		s0, w0 := render(toks[0])
		line, lineW := label+s0, labelW+w0
		for i := 1; i <= last; i++ {
			si, wi := render(toks[i])
			// Reserve 2 cols for a trailing " →" whenever more models follow, so a
			// break line's continuation arrow always fits within width instead of
			// being clipped at the edge; the final model needs no such reserve.
			budget := width
			if i < last {
				budget -= 2
			}
			if lineW+3+wi > budget { // won't fit — break after a trailing arrow
				out = append(out, line+stDim.Render(" →"))
				line, lineW = indent+si, labelW+wi
			} else {
				line += arrow + si
				lineW += 3 + wi
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n") + "\n"
}

// splitMeta peels the "thinking … · fallback … · advisor …" summary line off a
// routing block (if present), returning it trimmed plus the remaining role rows.
func splitMeta(rows []string) (string, []string) {
	if len(rows) > 0 && strings.Contains(rows[0], "·") && !modelRe.MatchString(rows[0]) {
		return strings.TrimSpace(rows[0]), rows[1:]
	}
	return "", rows
}

// ── generator facets ─────────────────────────────────────────────────────────
type facet struct {
	key    string
	values []string
	glyph  string
}

func facetDefs(glyphs map[string]string) []facet {
	return []facet{
		{"lane", []string{"gpt-only", "gpt-led", "mixed", "claude-led", "claude-only"}, glyphs["lane"]},
		{"model", []string{"fast", "normal", "smart"}, glyphs["model"]},
		{"thinking", []string{"minimal", "low", "medium", "high", "xhigh", "max"}, glyphs["thinking"]},
		// advisor as a power/cost dial: a quick glance, a proper review, or a
		// deep (expensive) audit — off spends nothing.
		{"advisor", []string{"off", "glance", "review", "audit"}, glyphs["advisor"]},
		{"fast", []string{"on", "off"}, glyphs["fast"]},
		{"spark", []string{"on", "off"}, glyphs["spark"]},
		{"fable", []string{"on", "off"}, glyphs["fable"]},
		// fable-as-main: hand the scarce elite the default (main-agent) role too.
		// A sub-setting of fable — only visible while fable is on (see
		// visibleFacets) and never set by a suggestion (see validFacetActions).
		{"main", []string{"on", "off"}, glyphs["main"]},
	}
}

// parseAdvisors reads the __advisors__ block (rows: "<level> <ctx> <chain>")
// into a map keyed "level/ctx" — the advisor model table, sourced from
// generate-profiles.py so the catalog stays a single source of truth.
func parseAdvisors(rows []string) map[string][]string {
	out := map[string][]string{}
	for _, r := range rows {
		f := strings.Fields(strings.ReplaceAll(r, "→", " "))
		if len(f) < 3 {
			continue
		}
		var chain []string
		for _, t := range f[2:] {
			if modelRe.MatchString(t) {
				chain = append(chain, t)
			}
		}
		if len(chain) > 0 {
			out[f[0]+"/"+f[1]] = chain
		}
	}
	return out
}

// modelFact is a model's measured facts from omp (via the catalog): pricing
// ($/1M tokens), output throughput (tok/s), and time-to-first-token (seconds).
type modelFact struct {
	in, out, speed, ttft float64
}

// effTPS folds ttft into throughput — the effective tok/s for a representative
// reply of effTokens: total time = ttft (startup) + tokens/speed (streaming), so
// a blazing-but-slow-to-start model (spark: 287 t/s, 5.6s ttft) reads honestly.
const effTokens = 300.0

func (f modelFact) effTPS() float64 {
	if f.speed <= 0 {
		return 0
	}
	return effTokens / (f.ttft + effTokens/f.speed)
}

// parseFacts reads the __models__ block (rows: "<id> <in> <out> <speed> <ttft>")
// into a per-model table, sourced from the catalog so meters and routing agree.
func parseFacts(rows []string) map[string]modelFact {
	out := map[string]modelFact{}
	for _, r := range rows {
		f := strings.Fields(r)
		if len(f) < 5 {
			continue
		}
		in, e1 := strconv.ParseFloat(f[1], 64)
		outc, e2 := strconv.ParseFloat(f[2], 64)
		sp, e3 := strconv.ParseFloat(f[3], 64)
		tt, e4 := strconv.ParseFloat(f[4], 64)
		if e1 == nil && e2 == nil && e3 == nil && e4 == nil {
			out[f[0]] = modelFact{in, outc, sp, tt}
		}
	}
	return out
}

// ── cost + speed meters ──────────────────────────────────────────────────────
// A profile's price and pace are dominated by the models on its heaviest roles,
// so each role is weighted by the token volume it drives over a session: the
// default agent and its task sub-agents move the needle; commit/tiny barely
// register — so Fable-as-commit stays cheap while Fable-as-default is dear (and
// slow). Per role, cost blends input+output pricing while speed reads the model's
// effective throughput (tok/s folded with time-to-first-token — see effTPS); both
// scale with thinking effort (more reasoning = pricier + slower) and take OpenAI's
// priority tier under fast mode (pricier but quicker). The weighted averages map
// onto 1..5 log scales (both perceived multiplicatively), calibrated across every
// valid facet × advisor × fast combination.
var roleWeight = map[string]float64{
	"default": 10, "task": 6, "reviewer": 3, "sonic": 3, "plan": 3, "advisor": 4,
	"slow": 2, "designer": 2, "librarian": 2, "smol": 1, "tiny": 0.5, "commit": 0.5,
}
var thinkMult = map[string]float64{ // reasoning tokens grow with effort → pricier
	"minimal": 0.6, "low": 0.8, "medium": 1.0, "high": 1.3, "xhigh": 1.6, "max": 2.0,
}
var thinkSpeed = map[string]float64{ // more reasoning before the answer → slower
	"minimal": 1.4, "low": 1.2, "medium": 1.0, "high": 0.8, "xhigh": 0.65, "max": 0.5,
}

const (
	priorityMult = 1.9 // OpenAI priority tier costs more under fast mode …
	fastSpeed    = 1.3 // … but responds quicker
)

// Ln endpoints of the grid-wide min/max weighted indices, calibrated over every
// valid facet × advisor × fast combination (cost dear→ high, speed fast→ high).
const (
	costLnLo, costLnHi   = 1.27, 4.42
	speedLnLo, speedLnHi = 2.49, 4.20
)

// weightedModels walks the current config's rows and calls fn(weight, id, level)
// for each role's lead model — the shared basis for both meters.
// currentRows is the routing block the cost/speed meters score: the generator's
// facet combo with the advisor dial applied.
func (m model) currentRows() []string {
	return m.applyAdvisor(m.generated[comboID(m.sel)], m.sel["advisor"])
}

func (m model) weightedModels(rows []string, fn func(w float64, id, lvl string)) {
	for _, r := range rows {
		f := strings.Fields(strings.ReplaceAll(r, "→", " "))
		i := 0
		if len(f) > 0 && f[0] == "●" {
			i = 1
		}
		if i >= len(f) {
			continue
		}
		w, ok := roleWeight[f[i]]
		if !ok {
			continue
		}
		var lead string
		for _, t := range f[i+1:] {
			if modelRe.MatchString(t) {
				lead = t
				break
			}
		}
		id, lvl, _ := strings.Cut(lead, ":")
		if id != "" {
			fn(w, id, lvl)
		}
	}
}

func logScore(idx, lnLo, lnHi float64) int {
	s := 1 + 4*(math.Log(idx)-lnLo)/(lnHi-lnLo)
	return int(math.Round(math.Max(1, math.Min(5, s))))
}

// costScore rates the current config from 1 (cheap) to 5 (dear).
func (m model) costScore() int {
	fast := m.sel["fast"] == "on" && m.sel["lane"] != "claude-only"
	var num, den float64
	m.weightedModels(m.currentRows(), func(w float64, id, lvl string) {
		c, ok := m.facts[id]
		if !ok {
			return
		}
		mult, ok := thinkMult[lvl]
		if !ok {
			mult = 1
		}
		cost := (0.25*c.in + 0.75*c.out) * mult
		if fast && strings.HasPrefix(id, "gpt-") {
			cost *= priorityMult
		}
		num += w * cost
		den += w
	})
	if den == 0 {
		return 1
	}
	return logScore(num/den, costLnLo, costLnHi)
}

// speedScore rates the current config from 1 (slow) to 5 (fast).
func (m model) speedScore() int {
	fast := m.sel["fast"] == "on" && m.sel["lane"] != "claude-only"
	var num, den float64
	m.weightedModels(m.currentRows(), func(w float64, id, lvl string) {
		c, ok := m.facts[id]
		if !ok || c.speed == 0 {
			return
		}
		mult, ok := thinkSpeed[lvl]
		if !ok {
			mult = 1
		}
		sp := c.effTPS() * mult
		if fast && strings.HasPrefix(id, "gpt-") {
			sp *= fastSpeed
		}
		num += w * sp
		den += w
	})
	if den == 0 {
		return 3
	}
	return logScore(num/den, speedLnLo, speedLnHi)
}

// meter renders a labelled 1..5 scale — n glyphs in the fill colour, the rest in
// the dim "empty" colour — always five glyphs so the fill (and the headroom) read
// at a glance.
func (m model) meter(label, glyph, fill string, n int) string {
	return clikit.Meter(label, glyph, fill, n)
}

// advisorChain returns the advisor role's model chain for an intensity, sourced
// from the baked __advisors__ table. The advisor is the independent second
// opinion, so it uses the opposite provider to whoever leads the session: GPT
// when the lead is Claude — a Claude-led (or pure-GPT) lane, or fable-as-main
// handing the default role to Fable — and Claude otherwise. Only the pure lanes
// stay on their own provider (gpt-only keeps GPT; claude-only keeps Claude).
func (m model) advisorChain(level string) []string {
	lane := m.sel["lane"]
	ctx := "claude"
	if lane == "gpt-only" || lane == "claude-led" {
		ctx = "gpt"
	}
	// fable-as-main puts Claude Fable in the default seat, so the second
	// opinion flips to GPT — except on claude-only, where the pure-lane rule
	// keeps the whole pool (advisor included) on Claude.
	if lane != "claude-only" && m.sel["fable"] == "on" && m.sel["main"] == "on" {
		ctx = "gpt"
	}
	return m.advisors[level+"/"+ctx]
}

// roleOf returns the role name of a routing row ("● task" → "task").
func roleOf(row string) string {
	f := strings.Fields(row)
	if len(f) > 0 && f[0] == "●" {
		f = f[1:]
	}
	if len(f) > 0 {
		return f[0]
	}
	return ""
}

// applyAdvisor replaces the baked advisor row with one synthesised from the
// chosen intensity (dropping it entirely when off), so the generated preview and
// the launched config both reflect the advisor facet.
func (m model) applyAdvisor(rows []string, level string) []string {
	chain := m.advisorChain(level)
	newRow := ""
	if len(chain) > 0 {
		newRow = "    advisor    " + strings.Join(chain, " → ")
	}
	var out []string
	replaced := false
	for _, r := range rows {
		if roleOf(r) == "advisor" {
			replaced = true
			if newRow != "" {
				out = append(out, newRow)
			}
			continue
		}
		out = append(out, r)
	}
	if !replaced && newRow != "" {
		out = append(out, newRow)
	}
	return out
}

// visibleFacets drops facets that don't apply to the current lane, so the
// generator only ever shows actionable options: no spark/fast on a Claude-only
// pool, no fable on a GPT-only pool. main is fable's sub-setting, so it only
// shows while fable is on (and the lane can host it at all).
func (m model) visibleFacets() []facet {
	lane := m.sel["lane"]
	var out []facet
	for _, f := range m.facets {
		if lane == "claude-only" && (f.key == "spark" || f.key == "fast") {
			continue
		}
		if lane == "gpt-only" && (f.key == "fable" || f.key == "main") {
			continue
		}
		if f.key == "main" && m.sel["fable"] != "on" {
			continue
		}
		out = append(out, f)
	}
	return out
}

func comboID(sel map[string]string) string {
	lane := sel["lane"]
	sp, fb := sel["spark"], sel["fable"]
	if lane == "gpt-only" {
		fb = "off"
	}
	if lane == "claude-only" {
		sp = "off"
	}
	spid, faid := "nosp", "nofa"
	if sp == "on" {
		spid = "sp"
	}
	if fb == "on" {
		faid = "fa"
		if sel["main"] == "on" {
			faid = "famain"
		}
	}
	return fmt.Sprintf("%s_%s_%s_%s_%s", lane, sel["model"], sel["thinking"], spid, faid)
}

func laneColor(lane string) string {
	switch lane {
	case "gpt-only":
		return "#3f8ef0" // deeper blue — pure pool
	case "gpt-led":
		return "#7ab6ff" // lighter blue — leans GPT
	case "mixed":
		return "#aa96e1"
	case "claude-led":
		return "#ffb277" // lighter orange — leans Claude
	case "claude-only":
		return "#ff8534" // deeper orange — pure pool
	}
	return "#ff9f52"
}

func prefixed(model string) string {
	if strings.HasPrefix(model, "claude") {
		return "anthropic/" + model
	}
	return "openai-codex/" + model
}

// genConfigYAML reconstructs an omp config (modelRoles, task-agent model
// overrides for the ●-marked agent-backed roles, fallback chains, thinking,
// advisor, and the priority tier when fast is on) from the generated routing
// block for the current facets — what Enter launches omp with. The agent
// overrides mirror the preview: without them the static managed defaults
// would keep the five agent-backed types pinned regardless of the generated
// profile (issue #173).
func (m model) genConfigYAML() string {
	rows := m.applyAdvisor(m.generated[comboID(m.sel)], m.sel["advisor"])
	var mr, fc, ao strings.Builder
	advisorOn := false
	for _, r := range rows {
		f := strings.Fields(strings.ReplaceAll(r, "→", " "))
		i := 0
		if len(f) > 0 && f[0] == "●" {
			i = 1
		}
		if i >= len(f) {
			continue
		}
		role := f[i]
		var models []string
		for _, t := range f[i+1:] {
			if modelRe.MatchString(t) {
				models = append(models, t)
			}
		}
		if len(models) == 0 {
			continue
		}
		if role == "advisor" {
			advisorOn = true
		}
		if i == 1 && role != "advisor" {
			// ●-marked agent-backed role: mirror its lead route as the task-agent
			// model override so spawned agents follow the generated profile.
			ao.WriteString("    " + role + ": " + prefixed(models[0]) + "\n")
		}
		mr.WriteString("  " + role + ": " + prefixed(models[0]) + "\n")
		if len(models) > 1 {
			var fbs []string
			for _, x := range models[1:] {
				fbs = append(fbs, prefixed(x))
			}
			fc.WriteString("    " + role + ": [" + strings.Join(fbs, ", ") + "]\n")
		}
	}
	var b strings.Builder
	b.WriteString("modelRoles:\n" + mr.String())
	b.WriteString("retry:\n  enabled: true\n  modelFallback: true\n  fallbackRevertPolicy: cooldown-expiry\n  fallbackChains:\n" + fc.String())
	if ao.Len() > 0 {
		b.WriteString("task:\n  agentModelOverrides:\n" + ao.String())
	}
	b.WriteString("defaultThinkingLevel: " + m.sel["thinking"] + "\n")
	if advisorOn {
		b.WriteString("advisor:\n  enabled: true\n")
	} else {
		b.WriteString("advisor:\n  enabled: false\n")
	}
	if m.sel["fast"] == "on" && m.sel["lane"] != "claude-only" {
		b.WriteString("tier:\n  openai: priority\n")
	}
	return b.String()
}

// ── model ────────────────────────────────────────────────────────────────────
// layout modes, chosen from the terminal size (unless the user collapses):
//
//	split     — wide:   the focused list on the left, routing preview on the
//	            right, and Usage spanning the full bottom width
//	medium    — generator-dominant: the list full width on top (primary), then
//	            Usage and Routing side by side in a secondary row — Usage's
//	            provider groups stacked vertically inside its measured left
//	            column, Routing on the right (and taking the whole row while
//	            ‹s› hides Usage)
//	collapsed — narrow/short or ‹p›: one full-width panel at a time (list, or
//	            routing w/ showResult) — the Generator stays usable instead of
//	            compressing every section into an unreadable split
const (
	modeSplit = iota
	modeMedium
	modeCollapsed
)

// size classes behind mode(): derived from terminal cells and the measured
// rendered minima of each section (#197) — never from pixels or a hard-coded
// screenshot width.
const (
	sizeWide = iota
	sizeMedium
	sizeNarrow
)

// gut is the left gutter every panel shares, so the whole UI hangs off one
// consistent margin instead of a ragged mix of flush-left and indented rows.
// topGap is the matching vertical breathing room above the section tabs.
// headRows counts the section head (tabs + blank separator) above a list body.
const (
	gut      = 2
	topGap   = 1
	headRows = 2
	// the launch footer pinned under the list: blank + cost + speed + blank +
	// the ⏎ launch action on its own visually separated row.
	launchFooterRows = 5
	// routingMinW is the narrowest useful routing column: pane chrome plus room
	// for a lead chain — below this a side-by-side routing panel stops earning
	// its keep.
	routingMinW = 33
	// secSepW is the one-cell border column between medium's adjacent
	// secondary panes (Usage left, Routing right) — visible separation, same
	// stroke as the wide layout's routing pane border.
	secSepW = 1
	// genMinRows is the fewest facet rows the generator list may be windowed to
	// before the layout must shed secondary sections instead of compressing it.
	genMinRows = 4
	// minRouteRows is the fewest routing viewport rows worth pinning chrome around.
	minRouteRows = 4
)

// genColMinH is the generator column's minimum useful height: the pinned head,
// a windowed-but-usable slice of the facet list, and the pinned launch footer.
const genColMinH = headRows + genMinRows + launchFooterRows

// genRowWidth is the width needed to render the widest generator facet row (all
// options) on a single line — the minimum for the left panel.
func (m model) genRowWidth() int {
	max := 30
	for _, f := range m.facets { // widest over ALL facets, so width is lane-stable
		w := 14 // ▸ + glyph + spaces + padded label
		for _, v := range f.values {
			w += len(v) + 4
		}
		if w > max {
			max = w
		}
	}
	return max + 2
}

// sizeMode classifies the terminal into the wide / medium / narrow-short
// responsive classes. Widths compare against the measured generator row,
// routing, and usage-column minima; heights against the chrome each composition
// pins on screen — breakpoints track content needs, not screenshot numbers.
func (m model) sizeMode() int {
	if m.w >= m.genRowWidth()+routingMinW && m.h >= m.wideMinH() {
		return sizeWide
	}
	if m.w >= m.mediumMinW() && m.h >= m.mediumMinH() {
		return sizeMedium
	}
	return sizeNarrow
}

func (m model) mode() int {
	if m.collapse {
		return modeCollapsed
	}
	switch m.sizeMode() {
	case sizeWide:
		return modeSplit
	case sizeMedium:
		return modeMedium
	default:
		return modeCollapsed
	}
}

// wideMinH is the least height at which the wide composition stays readable:
// a usable generator column above the full-width Usage footer. Shorter than
// this, keeping every section visible would compress them all — shed instead.
func (m model) wideMinH() int {
	return topGap + genColMinH + m.footerH(!m.hideUsage)
}

// mediumMinH stacks the generator over the secondary Routing+Usage row (at its
// measured minimum) with Usage out of the footer.
func (m model) mediumMinH() int {
	return topGap + genColMinH + 1 + m.secondaryMinH() + m.footerH(false)
}

// mediumMinW: the secondary row must seat a useful routing viewport beside the
// measured usage column — plus the one-cell separator between them — without
// clipping either.
func (m model) mediumMinW() int {
	if m.hideUsage {
		return routingMinW
	}
	return routingMinW + secSepW + m.usageColW()
}

// footerH measures the pinned footer for a composition directly from its parts
// — mode selection depends on it, so it must not consult the mode itself.
func (m model) footerH(withUsage bool) int {
	h := 1 + lipgloss.Height(padLeft(m.help.View(keys), gut))
	if withUsage {
		if p := m.usagePanel(); p != "" {
			h += 1 + lipgloss.Height(p)
		}
	}
	return h
}

// bodyH is the height available above the pinned footer.
func (m model) bodyH() int {
	h := m.h - lipgloss.Height(m.footer())
	if h < 1 {
		h = 1
	}
	return h
}

// contentH is the height the panels actually fill — bodyH minus the top gap.
func (m model) contentH() int {
	h := m.bodyH() - topGap
	if h < 1 {
		h = 1
	}
	return h
}

// bodyLines renders the generator's scrolling facet list and reports the cursor's
// line index within it.
func (m model) bodyLines() ([]string, int) {
	return m.genLines()
}

// launchFooter is the cost/speed meters for the current facet combo plus the
// enter-to-launch call to action — so the generator always shows what the choice
// costs, how fast it is, and how Enter will launch it. Enter always launches
// the generated profile for the current facets (the untouched default combo is
// a profile like any other); m runs omp-managed on the managed defaults with
// no overlay, and the sandbox (u) key is always offered.
func (m model) launchFooter() []string {
	cs, ss := m.costScore(), m.speedScore()
	acc := lipgloss.NewStyle().Foreground(lipgloss.Color(m.accent())).Bold(true).Render("  ⏎ launch")
	return []string{
		"",
		m.meter("cost", "$", meterRamp[cs], cs), // dear → red, cheap → green
		m.meter("speed", "»", meterRamp[6-ss], ss), // fast → green, slow → red
		"", // breathing room between the meters and the action row
		acc + stDim.Render("   m managed omp · u sandbox"),
	}
}

// mediumSplit gives the Routing+Usage row only its measured minimum, then lets
// the primary Generator absorb every remaining row. The medium height threshold
// guarantees both sections fit; taller terminals therefore expand Generator
// instead of leaving slack below the compact secondary content.
func (m model) mediumSplit(bodyH int) (genH, secH int) {
	secH = m.secondaryMinH()
	genH = bodyH - 1 - secH
	if genH < genColMinH {
		genH = genColMinH
		secH = bodyH - 1 - genH
	}
	return
}

// previewDims returns the preview viewport's inner (width, height) for the mode.
// The full-width modes reserve the shared gutter; split leaves the preview's own
// border + padding to do the breathing. Every mode reserves prevChromeRows for
// the pinned pill head above and fallback-display hint below the viewport.
func (m model) previewDims() (int, int) {
	bodyH := m.contentH()
	switch m.mode() {
	case modeCollapsed:
		return m.w - gut, bodyH - prevChromeRows
	case modeMedium:
		_, secH := m.mediumSplit(bodyH)
		return m.routingColW() - gut, secH - prevChromeRows
	default: // split — the pane draws a border + prevPadL inside its width, so the
		// viewport (what renderRoute wraps to) gets the inner text area, not the box.
		return m.w - m.listW() - 3 - prevPadL, bodyH - prevChromeRows
	}
}

// usageColShare is the medium secondary row's Usage width: Usage is the
// favored pane — it takes the larger 3/5 proportional share of the row so its
// bars and notes keep breathing room, never dropping below its measured
// stacked minimum. Routing is the pane that shrinks as Usage grows, floored
// at routingMinW (the medium width threshold guarantees both floors seat).
func (m model) usageColShare() int {
	avail := m.w - secSepW
	uw := avail * 3 / 5
	if min := m.usageColW(); uw < min {
		uw = min
	}
	if avail-uw < routingMinW {
		uw = avail - routingMinW
	}
	return uw
}

// routingColW is the medium secondary row's routing share: whatever Usage's
// favored share (and the separator between the panes) leaves free.
func (m model) routingColW() int {
	w := m.w
	if !m.hideUsage {
		w -= m.usageColShare() + secSepW
	}
	if w < routingMinW {
		w = routingMinW
	}
	return w
}

// ── trackpad / mouse wheel ───────────────────────────────────────────────────
// The wheel drives the generator directly: vertical scroll moves the facet
// selection, horizontal scroll changes the selected facet's value. Terminal
// mouse protocols expose direction-only press events rather than trackpad
// distance, so require a small burst before committing one generator step.
// This gives fine Mac trackpad motion room to settle without making every raw
// event select a new row or option. Routing remains continuous and ungated.
const (
	wheelStepEvents = 5
	wheelGestureGap = 200 * time.Millisecond
)

const (
	wheelAxisNone = iota
	wheelAxisV
	wheelAxisH
)

// admittedWheelMsg marks a generator wheel event whose same-direction burst
// crossed the step threshold before Bubble Tea's Update/render cycle.
type admittedWheelMsg struct{ tea.MouseMsg }

// wheelTarget is the layout state the pre-dispatch filter needs. Keeping this
// interface narrow also lets the raw-input regression test wrap model while
// preserving the exact production filter path.
type wheelTarget interface {
	wheelInRouting(int, int) bool
	routingWheelCanMove(tea.MouseButton) bool
}

// wheelInputFilter removes mouse traffic before Bubble Tea's unconditional
// redraw-after-Update. Generator motion accumulates by axis and direction;
// only each complete threshold reaches Update. Motion, non-wheel presses,
// routing horizontal wheel, and clamped routing scroll are dropped because
// none can change the view.
type wheelInputFilter struct {
	axis   int
	button tea.MouseButton
	count  int
	last   time.Time
}

func (f *wheelInputFilter) Filter(app tea.Model, msg tea.Msg) tea.Msg {

	mouse, ok := msg.(tea.MouseMsg)
	if !ok {
		return msg
	}
	if mouse.Action != tea.MouseActionPress {
		return nil
	}
	target, ok := app.(wheelTarget)
	if !ok {
		return msg
	}
	if target.wheelInRouting(mouse.X, mouse.Y) {
		switch mouse.Button {
		case tea.MouseButtonWheelUp, tea.MouseButtonWheelDown:
			if target.routingWheelCanMove(mouse.Button) {
				return mouse
			}
		}
		return nil
	}

	axis := wheelAxisNone
	switch mouse.Button {
	case tea.MouseButtonWheelUp, tea.MouseButtonWheelDown:
		axis = wheelAxisV
	case tea.MouseButtonWheelLeft, tea.MouseButtonWheelRight:
		axis = wheelAxisH
	default:
		return nil
	}
	now := time.Now()
	if f.count > 0 && now.Sub(f.last) <= wheelGestureGap && axis != f.axis {
		// Ignore brief orthogonal trackpad jitter without discarding progress
		// along the operator's dominant gesture axis.
		return nil
	}
	if axis != f.axis || mouse.Button != f.button || now.Sub(f.last) > wheelGestureGap {
		f.axis = axis
		f.button = mouse.Button
		f.count = 0
	}
	f.last = now
	f.count++
	if f.count < wheelStepEvents {
		return nil
	}
	f.count = 0
	return admittedWheelMsg{MouseMsg: mouse}
}

type model struct {
	generated map[string][]string
	advisors  map[string][]string  // "level/ctx" → advisor model chain
	facts     map[string]modelFact // model id → cost ($/1M) + curated speed (tok/s)
	avail     availability
	glyphs    map[string]string

	depth      int  // 0 lead · 1 full
	collapse   bool // p: hide the Routing section
	showResult bool // in collapsed mode: show the preview full-width
	hideUsage  bool // s: hide the Usage section (#198); fetch state keeps running unseen
	showUsage  bool // narrow mode: show Usage full-screen instead of silently shedding it

	facets         []facet
	fcur           int
	sel            map[string]string
	selectionState string // CODE_SELECTION_STATE; empty keeps standalone runs stateless

	vp       viewport.Model
	spin     spinner.Model
	help     help.Model
	w, h     int
	rdy      bool
	usageCmd string

	vaults       []vault
	selected     string                  // active vault id
	disabled     map[string]bool         // disabled vault ids (never includes the fallback)
	vaultState   string                  // CODE_AUTH_STATE path
	vaultErr     string                  // last vault switch/persist/login error
	vaultManifest string                  // resolved writable manifest path; empty for raw JSON/read-only
	managerInput  string                  // "create" or "rename" while manager text entry is active
	managerText   string                  // pending manager text-entry value
	vaultUsage   map[string]availability // per-vault usage snapshots for the manager
	manager      bool                    // v: the full-screen vault manager is open
	mgrCursor    int                     // manager row cursor
	loginRunning bool                    // one suspended provider login may run at a time

	fetching    bool      // a usage fetch is in flight (manual or auto)
	nextRefresh time.Time // when the next auto-refresh fires
	hadUsage    bool      // a successful fetch has landed for this profile — gates its first-load bar fill
	usageStale  bool      // the last refresh failed outright; avail is retained from an earlier success
	barAnim     int       // first-load fill frame (1..barAnimSteps-1 = partial); 0 = inactive, bars at full value

	launchManaged   bool              // m: run CODE_OMP with no overlay (the managed defaults)
	launchUntrusted bool              // u: run the CODE_OMP_UNTRUSTED sandbox
	genConfig       string            // generated config YAML to launch omp with (generator Enter)
	firstPrompt     string            // prompt from the suggest box, forwarded as omp's first message
	savedSel        map[string]string // selection snapshot before a live suggest preview (for revert)
}

// usage auto-refreshes on this cadence; a 1s tick drives the countdown.
const refreshEvery = 5 * time.Minute

type refreshTickMsg struct{}

func tickCmd() tea.Cmd {
	return tea.Tick(time.Second, func(time.Time) tea.Msg { return refreshTickMsg{} })
}

// usageMsg carries availability fetched off the main thread so startup never
// blocks on the usage command (a network call). The vault id travels with the
// result so a slow response is stored against its own vault: it can never
// overwrite the detailed panel of a vault that has since become active, and the
// manager keeps a per-vault snapshot regardless of which one is selected.
type usageMsg struct {
	vault string
	avail availability
}

func fetchUsageCmd(cmd string, v vault) tea.Cmd {
	if cmd == "" {
		return nil
	}
	return func() tea.Msg { return usageMsg{vault: v.ID, avail: loadAvailability(cmd, v)} }
}

// fetchAllCmd refreshes every vault at once — the manager's whole-list view.
func fetchAllCmd(cmd string, vaults []vault) tea.Cmd {
	var cmds []tea.Cmd
	for _, v := range vaults {
		if c := fetchUsageCmd(cmd, v); c != nil {
			cmds = append(cmds, c)
		}
	}
	if len(cmds) == 0 {
		return nil
	}
	return tea.Batch(cmds...)
}

// First-load bar fill: the per-profile-context animation that grows each usage
// bar from empty to its real value when the first successful fetch replaces the
// loading skeleton. A dedicated bounded tick sequence — barAnimSteps frames at
// barAnimInterval (8 × 25ms = 200ms total) — renders every bar's fill at
// step/steps of its target; labels and numbers are real from the first frame,
// only the fill animates. Manual and automatic refreshes for the same profile
// never re-run it, and each tick schedules nothing beyond the next frame.
const (
	barAnimSteps    = 8
	barAnimInterval = 25 * time.Millisecond
)

// barAnimMsg advances the first-load fill to the given frame (2..barAnimSteps).
type barAnimMsg struct{ step int }

func barAnimCmd(step int) tea.Cmd {
	return tea.Tick(barAnimInterval, func(time.Time) tea.Msg { return barAnimMsg{step} })
}

func (m model) Init() tea.Cmd {
	if m.usageCmd == "" {
		return nil
	}
	return tea.Batch(fetchUsageCmd(m.usageCmd, m.activeVault()), m.spin.Tick, tickCmd())
}

func (m model) listW() int {
	// wide enough for the generator options on one line; capped so a very wide
	// terminal doesn't stretch the list needlessly.
	w := m.genRowWidth()
	if w > m.w-33 {
		w = m.w - 33
	}
	if w > 80 {
		w = 80
	}
	return w
}

// gradient bar (green→red), 10 cells.
func barStr(p int) string {
	var r, g float64
	if p <= 50 {
		r, g = 90+float64(p)*3, 200
	} else {
		r, g = 235, 200-float64(p-50)*3
	}
	if r > 235 {
		r = 235
	}
	if g < 60 {
		g = 60
	}
	fill := (p*10 + 50) / 100
	if fill > 10 {
		fill = 10
	}
	if fill < 0 {
		fill = 0
	}
	filled := lipgloss.NewStyle().Foreground(lipgloss.Color(fmt.Sprintf("#%02x%02x46", clampByte(r), clampByte(g)))).Render(strings.Repeat("█", fill))
	return filled + stDim.Render(strings.Repeat("░", 10-fill))
}

func fmtReset(s int64) string {
	if s < 0 {
		s = 0
	}
	switch {
	case s >= 86400:
		return fmt.Sprintf("%dd%dh", s/86400, (s%86400)/3600)
	case s >= 3600:
		return fmt.Sprintf("%dh%dm", s/3600, (s%3600)/60)
	}
	return fmt.Sprintf("%dm", s/60)
}

func shortWin(l string) string {
	switch l {
	case "5 hours", "Claude 5 Hour":
		return "5h"
	case "7 days", "Claude 7 Day":
		return "7d"
	case "5 hours (Spark)":
		return "5h spark"
	case "7 days (Spark)":
		return "7d spark"
	case "Claude 7 Day (Fable)":
		return "7d fable"
	}
	return l
}

// usageCtrlLine is the Usage chrome's action row: the refresh status/countdown
// with its manual-refresh cue, then the profile-switch cue (omitted when only
// one auth profile exists). The identity itself lives in the provider group
// headings, so no separate auth equation remains (#198). A profile-switch
// error stays attached here — next to the control that caused it.
func (m *model) usageCtrlLine() string {
	var parts []string
	if m.usageCmd != "" {
		switch {
		case !m.avail.ok && (m.fetching || m.nextRefresh.IsZero()):
			parts = append(parts, stDim.Render(m.spin.View()+" fetching usage…"))
		case m.fetching:
			parts = append(parts, stWarn.Render(gReset+" refreshing…"))
		case m.usageStale:
			// A failed refresh kept the previous data on screen: the warning
			// takes the countdown's slot (same row, similar width) so the
			// measured panel geometry — and with it the medium/collapsed
			// breakpoint — barely moves on a flaky refresh.
			parts = append(parts, stWarn.Render("refresh failed · stale")+
				stDim.Render(" · ")+stKey.Render("r")+stDim.Render(" retry"))
		default:
			rem := time.Until(m.nextRefresh)
			if rem < 0 {
				rem = 0
			}
			s := int(rem.Seconds())
			parts = append(parts,
				stDim.Render(fmt.Sprintf("next refresh %d:%02d · ", s/60, s%60))+
					stKey.Render("r")+stDim.Render(" now"))
		}
	}
	if m.enabledCount() > 1 {
		parts = append(parts, stKey.Render("a")+stDim.Render(" switch vault"))
	}
	if len(parts) == 0 {
		return ""
	}
	line := "  " + strings.Join(parts, stDim.Render("  ·  "))
	if m.vaultErr != "" {
		line += "\n" + stBrk.Render("  vault switch failed: "+m.vaultErr)
	}
	return line
}

// providerHeading names a provider usage group without deriving identity from
// configured vault owner labels. Account identity is rendered separately from
// the broker's redacted snapshot.
func providerHeading(prov string) string {
	col, name := "#62a7ff", "Codex"
	if prov == "anthropic" {
		col, name = "#ff9f52", "Claude"
	}
	return lipgloss.NewStyle().Foreground(lipgloss.Color(col)).Bold(true).Render(name)
}

// providerAccountRows renders only identities reported by the broker's
// redacted snapshot. Email is preferred; the snapshot identity key is used
// when a connected account has no email. Sorting the copied display values
// keeps injected, cached, and fetched account sets deterministic without
// deriving identity from configured owner labels.
func providerAccountRows(a availability, prov string, checking bool) []string {
	if checking {
		return []string{stDim.Render("  checking account…")}
	}
	if !a.accountsOK {
		return []string{stWarn.Render("  account status unavailable")}
	}
	accounts := a.accounts[prov]
	if len(accounts) == 0 {
		return []string{stBrk.Render("  not authenticated")}
	}
	identities := make([]string, 0, len(accounts))
	unknown := 0
	for _, account := range accounts {
		identity := account.Email
		if identity == "" {
			identity = account.IdentityKey
		}
		if identity == "" {
			unknown++
			continue
		}
		identities = append(identities, identity)
	}
	sort.Strings(identities)
	rows := make([]string, 0, len(identities)+unknown+1)
	for _, identity := range identities {
		rows = append(rows, stDim.Render("  "+identity))
	}
	for range unknown {
		rows = append(rows, stDim.Render("  authenticated · identity unavailable"))
	}
	if a.accountsStale {
		rows = append(rows, stWarn.Render("  identity cached"))
	}
	return rows
}

func providerIdentityBlock(a availability, prov string, checking bool) []string {
	rows := []string{padLeft(providerHeading(prov), gut)}
	rows = append(rows, providerAccountRows(a, prov, checking)...)
	return rows
}

// identityLines keeps provider and broker-reported account state visible even
// when no usage rows exist.
func (m *model) identityLines() string {
	var lines []string
	for i, prov := range []string{"openai-codex", "anthropic"} {
		if i > 0 {
			lines = append(lines, "")
		}
		lines = append(lines, providerIdentityBlock(m.avail, prov, false)...)
	}
	return strings.Join(lines, "\n")
}

// usagePanel is the composition-agnostic Usage band sized for the current
// terminal width — the wide layout's full-width footer form.
func (m *model) usagePanel() string { return m.usagePanelFor(m.w) }

// usagePanelFor renders the first-class Usage section: the pilled title names
// the active vault and carries its local hide cue, followed by per-provider
// account lists and usage groups, then the refresh/switch control row at the
// section's bottom edge. Provider groups sit side by side only when w seats
// every column; w <= 0 forces the vertical stack used by medium layouts.
func (m *model) usagePanelFor(w int) string {
	v := m.activeVault()
	vaultName := v.Label
	if vaultName == "" {
		vaultName = v.ID
	}
	title := m.pill("usage")
	if vaultName != "" {
		title += stCue.Render(" · " + vaultName)
	}
	title += "  " + stCueKey.Render("s") + stCue.Render(" · hide")
	if len(m.vaults) > 1 {
		title += "  " + stCueKey.Render("v") + stCue.Render(" · vaults")
	}
	out := padLeft(title, gut) + "\n" +
		"\n" + m.usageBodyFor(w)
	if ctrl := m.usageCtrlLine(); ctrl != "" {
		out += "\n\n" + ctrl // blank row: air between provider content and the control row
	}
	return out
}

// usageBodyFor renders the provider/account content between the pinned title
// and the bottom control row: the identity-headed usage groups, or the
// loading/unavailable identity block.
func (m *model) usageBodyFor(w int) string {
	if !m.avail.ok {
		if m.usageLoading() {
			return m.skeletonBody(w)
		}
		out := m.identityLines()
		if m.usageCmd != "" && !m.fetching && !m.nextRefresh.IsZero() {
			out += "\n" + stWarn.Render("  usage unavailable · press v to manage vaults")
		}
		return out
	}
	if len(m.avail.wins) == 0 {
		return m.identityLines() + "\n" +
			stWarn.Render("  no provider usage · press v to manage vaults")
	}
	wins := append([]usageWin(nil), m.avail.wins...)
	provOrder := func(p string) int {
		switch p {
		case "openai-codex":
			return 0
		case "anthropic":
			return 1
		}
		return 2
	}
	tierOrder := func(t string) int {
		if t == "" || t == "-" {
			return 0
		}
		return 1
	}
	sort.SliceStable(wins, func(i, j int) bool {
		if o := provOrder(wins[i].prov) - provOrder(wins[j].prov); o != 0 {
			return o < 0
		}
		if o := tierOrder(wins[i].tier) - tierOrder(wins[j].tier); o != 0 {
			return o < 0
		}
		return wins[i].dur < wins[j].dur
	})
	blocks := map[string][]string{}
	var order []string
	for _, win := range wins {
		if _, ok := blocks[win.prov]; !ok {
			order = append(order, win.prov)
			blocks[win.prov] = providerIdentityBlock(m.avail, win.prov, false)
		}
		blocks[win.prov] = append(blocks[win.prov], m.usageRow(win))
	}
	if cl := m.creditLine(); cl != "" {
		if b, ok := blocks["openai-codex"]; ok {
			blocks["openai-codex"] = append(b, cl)
		}
	}
	return layoutGroups(w, order, blocks)
}

// layoutGroups arranges per-provider row blocks side by side when w seats
// every measured column, else stacked with a blank line between groups —
// shared by the real usage body and the loading skeleton so the two agree on
// geometry and the first fetch never pops the layout. colW must fit the
// widest row (label · bar · pct · ↻reset · note) without wrapping the note;
// a long broker-reported email widens the column instead of truncating it.
func layoutGroups(w int, order []string, blocks map[string][]string) string {
	colW := 49
	for _, prov := range order {
		for _, row := range blocks[prov] {
			if rowW := lipgloss.Width(row) + 2; rowW > colW {
				colW = rowW
			}
		}
	}
	if w > 0 && len(order) > 1 && w >= colW*len(order) {
		var cols []string
		for _, prov := range order {
			cols = append(cols, lipgloss.NewStyle().Width(colW).Render(strings.Join(blocks[prov], "\n")))
		}
		return lipgloss.JoinHorizontal(lipgloss.Top, cols...)
	}
	var lines []string
	for i, prov := range order {
		if i > 0 {
			lines = append(lines, "") // blank line between provider groups
		}
		lines = append(lines, blocks[prov]...)
	}
	return strings.Join(lines, "\n")
}

// usageLoading reports the initial-fetch state: a usage command exists but no
// successful result has ever landed and one is pending (in flight, or queued
// before the first tick) — the window where Usage shows the layout-stable
// skeleton instead of popping from an identity stub to full provider groups.
func (m *model) usageLoading() bool {
	return m.usageCmd != "" && !m.avail.ok && (m.fetching || m.nextRefresh.IsZero())
}

// skeletonWinsByProvider mirrors each provider's stable usage shape. Anthropic
// always reserves the Fable row, even before a first successful fetch.
var skeletonWinsByProvider = map[string][]string{
	"openai-codex": {"5h", "7d"},
	"anthropic":    {"5h", "7d", "7d fable"},
}

// skeletonRow is a placeholder usage row: the real row's exact geometry with
// an empty bar and ·· placeholders for the percentage and reset time.
func skeletonRow(label string) string {
	return fmt.Sprintf("  %-9s %s %s used  %s", label, barStr(0),
		stDim.Render(" ··%"), stDim.Render(gReset+" ····"))
}

// skeletonBody is the pre-first-fetch Usage content: provider headings,
// explicit checking state, and generic placeholder window rows, laid out by
// the same group logic as real data so the first result lands predictably.
func (m *model) skeletonBody(w int) string {
	order := []string{"openai-codex", "anthropic"}
	blocks := map[string][]string{}
	for _, prov := range order {
		rows := providerIdentityBlock(m.avail, prov, true)
		for _, label := range skeletonWinsByProvider[prov] {
			rows = append(rows, skeletonRow(label))
		}
		blocks[prov] = rows
	}
	return layoutGroups(w, order, blocks)
}

// usageColumn is the medium layout's left-hand Usage section: the panel with
// provider groups forced into a vertical stack — the column is deliberately
// too narrow for side-by-side groups. The panel carries its own title chrome.
func (m model) usageColumn() string {
	return m.usagePanelFor(0)
}

// usageColW is the medium usage column's measured width: the widest rendered
// line of the stacked panel (title, controls, bars, notes) — measured, not guessed.
func (m model) usageColW() int {
	return lipgloss.Width(m.usageColumn())
}

// secondaryMinH is the medium secondary row's minimum height: routing's pinned
// chrome plus a few useful route rows, or the full stacked usage column when
// that is taller — medium only engages when neither column needs clipping.
func (m model) secondaryMinH() int {
	h := prevChromeRows + minRouteRows
	if m.hideUsage {
		return h
	}
	if u := lipgloss.Height(m.usageColumn()); u > h {
		h = u
	}
	return h
}

func (m *model) usageRow(w usageWin) string {
	if w.missing {
		// Never-observed window (the upstream payload omits it): the real
		// row's exact geometry with dotted values, so the datum appearing on
		// a later refresh never pops the layout — no fabricated numbers.
		return skeletonRow(shortWin(w.label)) + "  " + stDim.Render("unavailable")
	}
	note := ""
	if w.pct >= 80 {
		note = "  " + stWarn.Render("tight")
	}
	if w.pct >= 100 {
		note = "  " + stBrk.Render("maxed")
	}
	if w.tier == "spark" && w.pct == 0 {
		note = "  " + lipgloss.NewStyle().Foreground(lipgloss.Color(cGreen)).Render("idle")
	}
	if w.stale {
		// Retained from the last successful fetch after a refresh omitted this
		// window. Keep the value and expose the observation timestamp.
		cached := "cached"
		if w.observed > 0 {
			cached += " " + time.Unix(w.observed, 0).Local().Format("15:04")
		}
		note += "  " + stWarn.Render(cached)
	}
	resetText := gReset + " " + pad(fmtReset(w.secs), 4)
	reset := stDim.Render(resetText)
	if w.dur > 0 && w.secs*10 < w.dur {
		reset = lipgloss.NewStyle().Foreground(lipgloss.Color("#c8d0dc")).Bold(true).Render(resetText)
	} else if w.dur > 0 && w.secs*4 < w.dur {
		reset = lipgloss.NewStyle().Foreground(lipgloss.Color("#c8d0dc")).Render(resetText)
	}
	// During the one-time first-load fill only the bar is scaled toward its
	// target; the label, percentage, and reset text are real from frame one.
	pct := w.pct
	if m.barAnim > 0 {
		pct = pct * m.barAnim / barAnimSteps
	}
	return fmt.Sprintf("  %-9s %s %3d%% used  %s%s", shortWin(w.label), barStr(pct), w.pct, reset, note)
}

// Reset-credit expiry urgency tints: each individual expiry (`3d`, `12d`, …)
// in the credit line is colored on a muted red→amber→green ramp so soon
// expiries read as warnings and distant ones as headroom, while the icon,
// count, and connecting prose stay dim. The palette is precomputed and
// deliberately desaturated (no per-frame color math, no saturated alarm
// colors inside a dim summary row); the day text itself stays sufficient
// without color. Thresholds are whole days remaining, exactly as fmtDays
// rounds them (up, so later-today = 1): ≤ creditUrgentDays is muted red,
// ≤ creditSoonDays muted amber, anything later muted green.
const (
	creditUrgentDays = 3  // expiring within three days — spend it or lose it
	creditSoonDays   = 10 // within ten days — plan around it
)

var (
	stCreditUrgent = lipgloss.NewStyle().Foreground(lipgloss.Color("#b0716f")) // muted red
	stCreditSoon   = lipgloss.NewStyle().Foreground(lipgloss.Color("#b39c6b")) // muted amber
	stCreditSafe   = lipgloss.NewStyle().Foreground(lipgloss.Color("#85a883")) // muted green
)

// creditDayStyle picks the urgency tint for a credit expiring in s seconds,
// bucketing on the same rounded-up whole days fmtDays renders — the color and
// the text can never disagree about which side of a threshold an expiry is on.
func creditDayStyle(s int64) lipgloss.Style {
	d := int64(0)
	if s > 0 {
		d = (s + 86399) / 86400
	}
	switch {
	case d <= creditUrgentDays:
		return stCreditUrgent
	case d <= creditSoonDays:
		return stCreditSoon
	default:
		return stCreditSafe
	}
}

// creditLine renders the OpenAI reset-credit summary: the available count and
// the days remaining until the three soonest credit expirations, ascending —
// each expiry tinted by creditDayStyle while the surrounding prose stays dim.
func (m *model) creditLine() string {
	c := m.avail.credits
	if c.avail == 0 && len(c.exp) == 0 {
		return ""
	}
	exp := append([]int64(nil), c.exp...)
	sort.Slice(exp, func(i, j int) bool { return exp[i] < exp[j] })
	if len(exp) > 3 {
		exp = exp[:3]
	}
	noun := "resets"
	if c.avail == 1 {
		noun = "reset"
	}
	line := stDim.Render(gReset + " " + fmt.Sprintf("%d %s", c.avail, noun))
	if len(exp) > 0 {
		days := make([]string, len(exp))
		for i, s := range exp {
			days[i] = creditDayStyle(s).Render(fmtDays(s))
		}
		line += stDim.Render(" · expiring in ") + strings.Join(days, stDim.Render(", "))
	}
	return "  " + line
}

// fmtDays renders a relative duration as whole days remaining, rounding up so
// a credit expiring later today still reads 1d.
func fmtDays(s int64) string {
	if s <= 0 {
		return "0d"
	}
	return fmt.Sprintf("%dd", (s+86399)/86400)
}

// syncPreview re-renders the routing content and jumps back to the top — for
// content changes (facet cycling, depth, reset), where the old scroll offset
// points at rows that no longer exist.
func (m *model) syncPreview() {
	m.syncPreviewAt(0)
}

// syncPreviewKeepScroll re-renders while preserving the scroll position where
// still valid — resizes and background usage refreshes must never yank the view.
func (m *model) syncPreviewKeepScroll() {
	m.syncPreviewAt(m.vp.YOffset)
}

func (m *model) syncPreviewAt(yoff int) {
	if !m.rdy || m.collapse {
		return
	}
	rw := m.vp.Width
	// No settings summary here: every dial is already visible (selected) in the
	// generator list on the left, so the preview shows only what that selection
	// produces — the role → model routing itself.
	var b strings.Builder
	id := comboID(m.sel)
	if base, ok := m.generated[id]; ok {
		_, roles := splitMeta(base)
		roles = m.applyAdvisor(roles, m.sel["advisor"])
		b.WriteString(renderRoute(roles, m.depth, m.avail, rw))
	} else {
		b.WriteString(stDim.Render("no profile for this combination") + "\n")
	}
	// clip (don't wrap) to pane width — renderRoute already wrapped the chains.
	content := lipgloss.NewStyle().MaxWidth(m.vp.Width).Render(b.String())
	m.vp.SetContent(content)
	m.vp.SetYOffset(yoff) // clamps into the new content and viewport height
}

// footer is the pinned bottom block: the usage panel (when this composition
// keeps Usage in the footer) then the controls help, each under a rule. Built
// once here so relayout and View stay in sync.
func (m *model) footer() string {
	rule := stDim.Render(strings.Repeat("─", m.w))
	var parts []string
	if m.usageInFooter() {
		if p := m.usagePanel(); p != "" {
			parts = append(parts, rule, p)
		}
	}
	parts = append(parts, rule, padLeft(m.help.View(m.contextHelp()), gut))
	return strings.Join(parts, "\n")
}

// usageInFooter says where Usage lives: the wide layout keeps it as the
// full-width bottom band; medium moves it into the secondary column (back to
// the footer while ‹p› hides that row); narrow/short hides it entirely so the
// Generator stays usable first — fetch state and the refresh cadence keep
// running unseen, and nothing is refetched when it reappears.
func (m *model) usageInFooter() bool {
	if m.hideUsage {
		return false
	}
	switch m.sizeMode() {
	case sizeWide:
		return true
	case sizeMedium:
		return m.collapse
	default:
		return false
	}
}

// routingShown reports whether the Routing section (and so its title-local
// p · hide cue) is on screen in the current composition.
func (m model) routingShown() bool {
	if m.showUsage && m.sizeMode() == sizeNarrow {
		return false
	}
	if m.collapse {
		return false
	}
	if m.mode() == modeCollapsed {
		return m.showResult
	}
	return true
}

// usageShown reports whether the Usage panel is rendered anywhere — the
// wide/collapsed footer band, medium's secondary column, or narrow's dedicated
// full-screen view.
func (m model) usageShown() bool {
	if m.hideUsage {
		return false
	}
	if m.sizeMode() == sizeNarrow {
		return m.showUsage
	}
	return m.usageInFooter() || m.mode() == modeMedium
}

// usageCanShow reports whether restoring Usage would actually render it.
// Narrow terminals use a dedicated full-width view when they can seat the
// stacked Usage column; extremely small terminals still suppress a dead cue.
func (m model) usageCanShow() bool {
	if m.sizeMode() == sizeNarrow {
		return m.w >= m.usageColW()
	}
	t := m
	t.hideUsage = false
	return t.usageShown()
}

// generatorShown: the Generator (and its launch footer advertising ⏎/m/u) is
// visible in every composition except a narrow full-screen secondary view.
func (m model) generatorShown() bool {
	if m.sizeMode() == sizeNarrow && m.showUsage {
		return false
	}
	return !(m.mode() == modeCollapsed && !m.collapse && m.showResult)
}

// helpKeys is the state-derived key map handed to the bubbles help view: the
// compact line lists only what contextHelp selected, while ? always exposes
// the complete static reference.
type helpKeys struct {
	short []key.Binding
	full  [][]key.Binding
}

func (h helpKeys) ShortHelp() []key.Binding  { return h.short }
func (h helpKeys) FullHelp() [][]key.Binding { return h.full }

// contextHelp derives the compact footer from the model state (#198):
//   - navigation, reset, full-help discovery, and quit are always offered;
//   - a hidden section contributes its recovery action (show routing/usage) —
//     usage only when the current terminal could actually seat it again;
//   - profile switching and manual refresh surface only while the Usage
//     chrome that normally advertises them is off screen, and only when they
//     can run (an alternate profile exists; no fetch already in flight);
//   - the launch trio surfaces only while the Generator launch footer is
//     hidden (the narrow routing-full-screen swap).
//
// Everything else lives in visible section chrome or behind ?.
func (m model) contextHelp() helpKeys {
	short := []key.Binding{keys.Move, keys.Change}
	// The generator title advertises d · defaults itself; the compact line
	// repeats it only while that chrome is off screen (routing full-screen).
	if !m.generatorShown() {
		short = append(short, keys.Reset)
	}
	if !m.routingShown() {
		short = append(short, key.NewBinding(key.WithKeys("p"), key.WithHelp("p", "show routing")))
	}
	if !m.usageShown() && m.usageCanShow() {
		short = append(short, key.NewBinding(key.WithKeys("s"), key.WithHelp("s", "show usage")))
	}
	// Keep full-help discovery and quit ahead of optional contextual actions:
	// bubbles truncates a compact line from the right on narrow terminals.
	short = append(short, keys.Help, keys.Quit)
	if !m.usageShown() {
		if m.enabledCount() > 1 {
			short = append(short, keys.Auth)
		}
		if len(m.vaults) > 1 {
			short = append(short, keys.Manager)
		}
		if m.usageCmd != "" && !m.fetching {
			short = append(short, keys.Refresh)
		}
	}
	if !m.generatorShown() {
		short = append(short, keys.Launch, keys.Managed, keys.Untrusted)
	}
	return helpKeys{short: short, full: keys.FullHelp()}
}

func (m *model) relayout() {
	m.help.Width = m.w - gut // the footer help is gutter-inset on every line; wrap inside the padded width
	pw, ph := m.previewDims()
	if pw < 10 {
		pw = 10
	}
	if ph < 3 {
		ph = 3
	}
	if !m.rdy {
		m.vp = viewport.New(pw, ph)
		m.rdy = true
	} else {
		m.vp.Width, m.vp.Height = pw, ph
	}
	m.syncPreviewKeepScroll()
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.w, m.h = msg.Width, msg.Height
		m.relayout()
	case usageMsg:
		if m.vaultUsage == nil {
			m.vaultUsage = map[string]availability{}
		}
		previous, known := m.vaultUsage[msg.vault]
		if !known && msg.vault == m.activeVault().ID {
			previous = m.avail
		}
		scoped, scopedStale := reconcileUsage(previous, msg.avail)
		m.vaultUsage[msg.vault] = scoped
		if msg.vault != m.activeVault().ID {
			return m, nil // not the active vault: never touches the detailed panel or its fill
		}
		first := !m.hadUsage && msg.avail.ok
		m.avail, m.usageStale = scoped, scopedStale
		m.hadUsage = m.hadUsage || msg.avail.ok
		m.fetching = false
		m.nextRefresh = time.Now().Add(refreshEvery)
		m.relayout()
		if first {
			// The first real data replaces the skeleton: run the one-time
			// bounded bar fill. Refreshes never reach this branch again.
			m.barAnim = 1
			return m, barAnimCmd(2)
		}
	case loginDoneMsg:
		m.loginRunning = false
		m.vaultErr = ""
		if msg.err != nil && !errors.Is(msg.err, errLoginCancelled) {
			m.vaultErr = "login failed: " + msg.err.Error()
		}
		for _, v := range m.vaults {
			if v.ID != msg.vault {
				continue
			}
			if v.ID == m.activeVault().ID {
				m.fetching = m.usageCmd != ""
			}
			return m, fetchUsageCmd(m.usageCmd, v)
		}
		return m, nil
	case barAnimMsg:
		// Bounded and self-terminating: apply the frame, arm the next tick,
		// and stop at the final step (barAnim 0 = inactive, bars at value).
		if m.barAnim == 0 {
			return m, nil
		}
		if msg.step >= barAnimSteps {
			m.barAnim = 0
			return m, nil
		}
		m.barAnim = msg.step
		return m, barAnimCmd(msg.step + 1)
	case refreshTickMsg:
		// re-arm the 1s tick; auto-refresh once the interval elapses.
		cmds := []tea.Cmd{tickCmd()}
		if !m.fetching && !m.nextRefresh.IsZero() && !time.Now().Before(m.nextRefresh) {
			m.fetching = true
			cmds = append(cmds, fetchUsageCmd(m.usageCmd, m.activeVault()))
		}
		return m, tea.Batch(cmds...)
	case spinner.TickMsg:
		if m.fetching || !m.avail.ok {
			var cmd tea.Cmd
			m.spin, cmd = m.spin.Update(msg)
			return m, cmd
		}
	case admittedWheelMsg:
		m.applyWheelStep(msg.Button)
		return m, nil
	case tea.MouseMsg:
		// Wheel dispatch by pointer position: inside the visible Routing pane
		// the viewport owns vertical scrolling — continuous, ungated, clamped
		// by the viewport itself, with horizontal wheel deliberately inert.
		// Everywhere else direct Update calls apply one generator step; live
		// input is coalesced before dispatch by wheelInputFilter.
		if msg.Action == tea.MouseActionPress {
			if m.wheelInRouting(msg.X, msg.Y) {
				switch msg.Button {
				case tea.MouseButtonWheelUp:
					m.vp.LineDown(1) // inverted: operator-confirmed trackpad direction
				case tea.MouseButtonWheelDown:
					m.vp.LineUp(1)
				}
				return m, nil
			}
			m.applyWheelStep(msg.Button)
		}
	case tea.KeyMsg:
		if m.manager {
			return m.updateManager(msg)
		}
		switch msg.String() {
		case "q", "esc", "ctrl+c":
			return m, tea.Quit
		case "p":
			switch {
			case m.showUsage && m.sizeMode() == sizeNarrow:
				m.showUsage = false
				m.showResult = true
				m.collapse = false
			case m.collapse:
				m.collapse = false // restore the hidden preview
			case m.mode() == modeCollapsed:
				m.showResult = !m.showResult // narrow+short: swap list ↔ result full-screen
			default:
				m.collapse = true // split/stacked: hide the preview, list full-screen
			}
			m.relayout()
		case "s":
			// Narrow terminals give Usage a dedicated full-screen view instead
			// of treating s as a hidden-state toggle that accidentally reveals
			// Routing. Wider layouts keep the inline section collapse.
			if m.sizeMode() == sizeNarrow {
				if m.showUsage {
					m.showUsage = false
					m.hideUsage = true
				} else {
					m.showUsage = true
					m.hideUsage = false
					m.showResult = false
					m.collapse = false
				}
			} else {
				m.showUsage = false
				m.hideUsage = !m.hideUsage
			}
			m.relayout()
		case "?":
			m.help.ShowAll = !m.help.ShowAll
			m.relayout() // the taller/shorter footer changes the body height
		case "d":
			m.sel = defaultSel()
			m.persistSelection()
			m.syncPreview()
		case "f":
			m.depth = (m.depth + 1) % 2
			m.syncPreview()
		case "r":
			if m.usageCmd != "" && !m.fetching {
				m.fetching = true
				return m, fetchUsageCmd(m.usageCmd, m.activeVault())
			}
		case "a":
			changed, err := m.cycleVault()
			if err != nil {
				m.vaultErr = err.Error()
				m.relayout()
				break
			}
			if changed {
				m.vaultErr = ""
				m.usageStale = false // the wiped avail belongs to the new vault; no stale carry-over
				m.fetching = m.usageCmd != ""
				m.relayout()
				if m.fetching {
					return m, fetchUsageCmd(m.usageCmd, m.activeVault())
				}
			}
		case "v":
			if len(m.vaults) > 0 {
				m.manager = true
				m.mgrCursor = m.activeIndex()
				m.fetching = m.usageCmd != ""
				m.relayout()
				return m, fetchAllCmd(m.usageCmd, m.vaults)
			}
		case "up", "k":
			m.moveUp()
		case "down", "j":
			m.moveDown()
		case "left", "h":
			m.cycleFacet(-1)
		case "right", "l":
			m.cycleFacet(1)
		case "u":
			// Untrusted sandbox: hand off to CODE_OMP_UNTRUSTED (ompu), which owns its
			// own routing/policy — no generated --config is passed to it.
			m.launchUntrusted = true
			return m, tea.Quit
		case "pgup", "ctrl+u":
			m.vp.HalfViewUp() // scroll the preview (mouse capture is off, see main)
		case "pgdown", "ctrl+d":
			m.vp.HalfViewDown()
		case "m":
			// Managed-defaults omp: omp-managed with no generated overlay. The
			// explicit keybind keeps every Enter launch a generated profile.
			m.launchManaged = true
			return m, tea.Quit
		case "enter":
			// Enter always launches the generated profile for the current facets —
			// the untouched default combo is a generated profile like any other.
			m.genConfig = m.genConfigYAML()
			return m, tea.Quit
		}

	case clikit.ActionsProposedMsg:
		// Live preview: snapshot the current selection, then apply the proposal to
		// the generator so the user sees the change while deciding. Report the FULL
		// applied diff back to the box (the model's picks plus the derived toggles),
		// so its "applied" list reflects everything that changed, not just the three
		// facets the model named directly.
		m.savedSel = map[string]string{}
		for k, v := range m.sel {
			m.savedSel[k] = v
		}
		m.applyActions(msg.Actions)
		return m, func() tea.Msg { return clikit.AppliedActionsMsg{Actions: m.appliedDiff()} }

	case clikit.ActionsConfirmedMsg:
		// Kept: the preview stays; remember the prompt for the launched session.
		m.savedSel = nil
		m.firstPrompt = msg.Prompt
		m.persistSelection()

	case clikit.ActionsRevertedMsg:
		// Rejected: restore the pre-preview selection.
		if m.savedSel != nil {
			m.sel = m.savedSel
			m.savedSel = nil
			m.syncPreview()
		}
	}
	return m, nil
}

// wheelInRouting reports whether a pointer position (terminal cells, 0-based)
// falls inside the visible Routing pane, whose viewport then owns vertical
// wheel scrolling: the wide split's right pane, medium's lower-right pane, or
// the narrow routing-only swap's full body. Hidden/collapsed routing claims
// nothing, so the generator keeps the wheel everywhere else.
func (m model) wheelInRouting(x, y int) bool {
	if !m.routingShown() {
		return false
	}
	ch := m.contentH()
	switch m.mode() {
	case modeCollapsed: // routing-only swap: the whole body is Routing
		return y >= topGap && y < topGap+ch
	case modeMedium: // the secondary row's right column, under the divider
		genH, secH := m.mediumSplit(ch)
		secTop := topGap + genH + 1
		return y >= secTop && y < secTop+secH && x >= m.w-m.routingColW()
	default: // split: the right pane, from the list's right edge on
		return y >= topGap && y < topGap+ch && x >= m.listW()
	}
}

// routingWheelCanMove reports whether a vertical routing scroll would change
// the viewport. No-op events at either clamp are filtered before redraw.
func (m model) routingWheelCanMove(b tea.MouseButton) bool {
	switch b {
	case tea.MouseButtonWheelUp:
		return m.vp.YOffset < m.vp.TotalLineCount()-m.vp.Height
	case tea.MouseButtonWheelDown:
		return m.vp.YOffset > 0
	default:
		return false
	}
}

// applyWheelStep translates one admitted wheel event into the matching facet
// action: vertical scroll moves the selection, horizontal scroll changes the
// value. The raw mapping is INVERTED on both axes — operator-confirmed trackpad
// direction: WheelUp moves the selection down, WheelDown up; WheelLeft cycles
// to the next (right) option, WheelRight to the previous. Arrow keys keep their
// literal semantics.
func (m *model) applyWheelStep(b tea.MouseButton) {
	switch b {
	case tea.MouseButtonWheelUp:
		m.moveDown()
	case tea.MouseButtonWheelDown:
		m.moveUp()
	case tea.MouseButtonWheelLeft:
		m.cycleFacet(1)
	case tea.MouseButtonWheelRight:
		m.cycleFacet(-1)
	}
}

func (m *model) moveUp() {
	if m.fcur > 0 {
		m.fcur--
	}
}
func (m *model) moveDown() {
	if m.fcur < len(m.visibleFacets())-1 {
		m.fcur++
	}
}
func (m *model) cycleFacet(dir int) {
	vf := m.visibleFacets()
	if m.fcur >= len(vf) {
		m.fcur = len(vf) - 1
	}
	f := vf[m.fcur]
	cur := m.sel[f.key]
	idx := 0
	for i, v := range f.values {
		if v == cur {
			idx = i
		}
	}
	next := idx + dir
	if next < 0 {
		next = 0
	} else if next >= len(f.values) {
		next = len(f.values) - 1
	}
	if next == idx {
		return
	}
	m.sel[f.key] = f.values[next]
	// main is fable's sub-setting: whenever fable leaves "on" it must clear too,
	// so a later fable re-enable never silently resurrects the (expensive)
	// fable-as-main escalation — it is re-chosen deliberately every time.
	if m.sel["fable"] != "on" {
		m.sel["main"] = "off"
	}
	// changing the lane can hide/show facets; keep the cursor in range.
	if nv := len(m.visibleFacets()); m.fcur >= nv {
		m.fcur = nv - 1
	}
	m.syncPreview()
	m.persistSelection()
}

// prevPadL is the split preview pane's left padding. Width() counts it, so the
// viewport's usable text width is the box width minus this — the viewport must
// be sized to that inner area (see previewDims), else lines wrap 1:1 with the
// box and their tail overflows to the pane's left edge.
const prevPadL = 2

func (m model) previewPane(w, h int) string {
	return lipgloss.NewStyle().
		Border(lipgloss.NormalBorder(), false, false, false, true).
		BorderForeground(lipgloss.Color(cBord)).PaddingLeft(prevPadL).
		Width(w).Height(h).
		Render(m.previewColumn())
}

// accent is the context colour — the selected lane in the generator.
// Blue / purple / orange.
func (m model) accent() string {
	return laneColor(m.sel["lane"])
}

// pill renders an accent-backed section label, coloured by the active lane —
// the shared shape of the generator (left) and routing (right) column heads.
func (m model) pill(label string) string {
	return lipgloss.NewStyle().Padding(0, 1).
		Background(lipgloss.Color(m.accent())).Foreground(lipgloss.Color("#12161d")).Bold(true).
		Render(label)
}

// sectionTitle is the accent-pilled "generator" label at the top of the left
// column.
func (m model) sectionTitle() string {
	return m.pill("generator")
}

// sectionHead is the gutter-inset title row — the pill plus its local
// reset-to-defaults cue (d · defaults) — and a blank separator (headRows
// tall); it stays pinned above the scrolling facet list.
func (m model) sectionHead() string {
	return padLeft(m.sectionTitle()+"  "+stCueKey.Render("d")+stCue.Render(" · defaults"), gut) + "\n\n"
}

// prevChromeRows is the Routing column's pinned chrome around the scrolling
// viewport: the title row with its local collapse cue and a blank separator
// above, plus the fallback-display cue pinned beneath the viewport.
const prevChromeRows = headRows + 1

// previewColumn assembles the Routing section: the pinned title row carrying
// the section-local collapse cue (p · hide), the scrolling routing viewport,
// then the fallback-display cue pinned at the section's bottom edge — bottom
// chrome, where the chains it toggles end. The f wording makes clear it only
// changes what is DISPLAYED: the launched profile always keeps its fallback
// chains.
func (m model) previewColumn() string {
	verb := "show"
	if m.depth == 1 {
		verb = "hide"
	}
	return m.pill("routing") + "  " + stCueKey.Render("p") + stCue.Render(" · hide") + "\n\n" +
		m.vp.View() + "\n" +
		stKey.Render("f") + stDim.Render(" · "+verb+" fallback chains")
}

// leftColumn renders the pinned section head plus the scrolling list body, the
// whole column inset by the shared gutter, sized to totalH rows and w columns.
func (m model) leftColumn(w, totalH int) string {
	iw := w - gut
	body, bcur := m.bodyLines()
	listH := totalH - headRows - launchFooterRows
	if listH < 1 {
		listH = 1
	}
	list := padLeft(windowList(body, bcur, listH, iw), gut)
	footer := padLeft(strings.Join(m.launchFooter(), "\n"), gut)
	return m.sectionHead() + list + "\n" + footer
}

// mediumContent is the generator-dominant layout: the full-width facet list on
// top (primary), a divider, then Usage (left) and Routing (right) side by side
// in a secondary row, separated by a one-cell border column. Usage stacks its
// provider groups vertically inside the measured-width left column; Routing
// keeps its own scrolling viewport in whatever the row leaves free.
func (m model) mediumContent(bodyH int) string {
	genH, secH := m.mediumSplit(bodyH)
	top := m.leftColumn(m.w, genH)
	div := stDim.Render(strings.Repeat("─", m.w))
	rw := m.routingColW()
	// clip each column before fixing its width — Width() alone would wrap any
	// over-wide line onto an extra physical row and break the row's height.
	routing := lipgloss.NewStyle().Width(rw).MaxHeight(secH).Render(
		lipgloss.NewStyle().MaxWidth(rw).Render(padLeft(m.previewColumn(), gut)))
	sec := routing
	if !m.hideUsage {
		uw := m.w - rw - secSepW // the measured usage column's share, left of the border
		sep := lipgloss.NewStyle().Foreground(lipgloss.Color(cBord)).Render(
			strings.TrimSuffix(strings.Repeat("│\n", secH), "\n"))
		usage := lipgloss.NewStyle().Width(uw).MaxHeight(secH).Render(
			lipgloss.NewStyle().MaxWidth(uw).Render(m.usageColumn()))
		sec = lipgloss.JoinHorizontal(lipgloss.Top, usage, sep, routing)
	}
	return lipgloss.JoinVertical(lipgloss.Left, top, div, sec)
}

func (m model) View() string {
	if !m.rdy {
		return "loading…"
	}
	if m.manager {
		return m.managerView()
	}
	foot := m.footer()
	bodyH := m.bodyH()
	ch := m.contentH()
	var content string
	switch m.mode() {
	case modeCollapsed:
		switch {
		case m.showUsage && m.sizeMode() == sizeNarrow:
			content = padLeft(m.usagePanelFor(m.w-gut), gut)
		case m.showResult && !m.collapse:
			content = padLeft(m.previewColumn(), gut)
		default:
			content = m.leftColumn(m.w, ch)
		}
	case modeMedium:
		content = m.mediumContent(ch)
	default: // split
		content = lipgloss.JoinHorizontal(lipgloss.Top,
			m.leftColumn(m.listW(), ch),
			m.previewPane(m.w-m.listW()-3, ch))
	}
	// Pin the body into a fixed box (top-left) with lipgloss, then clip: any
	// stray overflow (e.g. a glyph a terminal renders wider than measured) is
	// absorbed here, never pushing the pinned footer off-screen. A top gap above
	// the content gives the section tabs vertical breathing room.
	body := lipgloss.NewStyle().MaxHeight(bodyH).Render(
		strings.Repeat("\n", topGap) +
			lipgloss.Place(m.w, ch, lipgloss.Left, lipgloss.Top, content))
	return lipgloss.NewStyle().MaxWidth(m.w).MaxHeight(m.h).Render(
		lipgloss.JoinVertical(lipgloss.Left, body, foot))
}

func (m model) genLines() ([]string, int) {
	acc := m.accent()
	var lines []string
	cursor := 0
	for i, f := range m.visibleFacets() {
		onRow := i == m.fcur
		glyCol := laneColor(m.sel["lane"])
		gly := lipgloss.NewStyle().Foreground(lipgloss.Color(glyCol)).Width(2).Render(f.glyph)
		ptr := "  "
		if onRow {
			ptr = lipgloss.NewStyle().Foreground(lipgloss.Color(acc)).Render("▸ ")
			cursor = len(lines)
		}
		// main renders as fable's tabulated child "default": the indent + the
		// default-role row lighting up Fable in the preview explain themselves,
		// so it carries no flavor text (which would wrap on narrow panes anyway).
		label, childPad, childW := f.key, "", 0
		if f.key == "main" {
			// tree-style L connector: reads as fable's child, like `tree`.
			label, childPad, childW = "default", stDim.Render("└ "), 2
		}
		row := fmt.Sprintf("%s%s%s%s", ptr, childPad, gly, stDim.Render(pad(label, 9-childW)))
		for _, v := range f.values {
			switch {
			case v == m.sel[f.key]:
				col := acc
				if f.key == "lane" {
					col = laneColor(v)
				} else if (f.key == "spark" || f.key == "fable" || f.key == "main") && v == "on" {
					col = cGreen
				}
				st := lipgloss.NewStyle().Foreground(lipgloss.Color(col)).Bold(true)
				if onRow { // the cursor sits on the selected value of the focused row
					st = st.Background(lipgloss.Color(cSelBg))
				}
				row += "  " + st.Render(" "+v+" ")
			default:
				row += "   " + stDim.Render(v)
			}
		}
		switch {
		case (f.key == "fable" || f.key == "spark") && m.sel[f.key] == "on":
			bkt, lbl := "claude-fable", "Fable"
			if f.key == "spark" {
				bkt, lbl = "codex-spark", "Spark"
			}
			if m.avail.down(bkt) {
				w := lbl + " maxed · " + gReset + " " + fmtReset(m.avail.reset[bkt])
				if m.avail.bucket[bkt] == "unauthed" {
					w = lbl + " unavailable"
				}
				row += "   " + stWarn.Render(gWarn+" "+w+" — no usage left")
			}
		case f.key == "fast" && m.sel["fast"] == "on":
			row += "   " + stDim.Render("GPT only")
		}
		lines = append(lines, row)
	}
	return lines, cursor
}

// defaultGlyphs is the built-in facet-glyph set (Nerd Font, Font Awesome PUA
// range), written as explicit \u escapes so the codepoints stay visible and
// verifiable in source — a literal PUA glyph is invisible in most editors and
// was once wiped by an edit exactly because of that. CODE_FACET_GLYPHS may
// override any entry (see main).
//
//	lane ⇄ (f127)  model ⚙ (f085)  thinking 💡 (f0eb)  advisor 🧭 (f14e)
//	spark 🚀 (f135)  fable 📖 (f02d)  default 🎯 (f140)  fast ⚡ (f0e7)
func defaultGlyphs() map[string]string {
	return map[string]string{
		"lane": "\uf127", "model": "\uf085", "thinking": "\uf0eb", "advisor": "\uf14e",
		"spark": "\uf135", "fable": "\uf02d", "main": "\uf140", "fast": "\uf0e7",
	}
}

func main() {
	glyphs := defaultGlyphs()
	for _, kv := range strings.Split(os.Getenv("CODE_FACET_GLYPHS"), ",") {
		if p := strings.SplitN(kv, "=", 2); len(p) == 2 && p[1] != "" {
			glyphs[p[0]] = p[1]
		}
	}
	sp := spinner.New()
	sp.Spinner = spinner.Dot
	generated := loadBlocks(os.Getenv("CODE_GENERATED"))
	vaults, vaultManifest := resolveVaults(os.Getenv("CODE_AUTH_VAULTS"), os.Getenv("CODE_AUTH_VAULTS_FILE"))
	vaultState := os.Getenv("CODE_AUTH_STATE")
	selected, disabled := loadVaultState(vaults, vaultState)
	facets := facetDefs(glyphs)
	selectionState := os.Getenv("CODE_SELECTION_STATE")
	m := model{
		generated:      generated,
		advisors:       parseAdvisors(generated["__advisors__"]),
		facts:          parseFacts(generated["__models__"]),
		avail:          availability{bucket: map[string]string{}, reset: map[string]int64{}},
		usageCmd:       os.Getenv("CODE_USAGE"),
		vaults:         vaults,
		selected:       selected,
		disabled:       disabled,
		vaultState:     vaultState,
		vaultManifest:  vaultManifest,
		vaultUsage:     map[string]availability{},
		fetching:       os.Getenv("CODE_USAGE") != "",
		spin:           sp,
		help:           help.New(),
		glyphs:         glyphs,
		facets:         facets,
		sel:            loadSelectionState(selectionState, facets),
		selectionState: selectionState,
	}
	// Cell-motion mouse reporting carries wheel events. Filter rejected
	// momentum and unused motion before Bubble Tea's redraw-after-Update loop.
	inputFilter := &wheelInputFilter{}
	final, err := clikit.Run(m, clikit.WithAltScreen(), clikit.WithMouseCellMotion(),
		clikit.WithMessageFilter(inputFilter.Filter))
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	fm, _ := final.(model)
	switch {
	case fm.launchUntrusted:
		// The sandbox owns its own fixed profile and must never inherit the
		// selected vault's broker env — no forced default, no broker vars.
		runExec("CODE_OMP_UNTRUSTED", "ompu", sandboxLaunchArgv, fm.firstPrompt, nil)
	case fm.launchManaged:
		// m — omp-managed on the managed defaults, no generated overlay, on the
		// shared default client profile with the selected vault's broker env.
		runExec("CODE_OMP", "omp-managed", managedLaunchArgv, fm.firstPrompt, mustBrokerEnv(fm))
	case fm.genConfig != "":
		launchGenerated(fm.genConfig, fm.firstPrompt, mustBrokerEnv(fm))
	}
}

// mustBrokerEnv loads the active vault's broker environment for a trusted
// launch, aborting rather than launching with absent/stale credentials.
func mustBrokerEnv(m model) []string {
	env, err := brokerEnv(m.activeVault())
	if err != nil {
		fmt.Fprintln(os.Stderr, "code: vault token unavailable:", err)
		os.Exit(1)
	}
	return env
}

// forwardArgv builds an exec argv: the resolved path, the forwarded args with
// the given client profile forced (any forwarded --profile stripped first), and
// the optional trailing suggest-box prompt.
func forwardArgv(path, profile string, forwarded []string, prompt string) []string {
	out := append([]string{path}, withOMPProfile(profile, forwarded...)...)
	if prompt != "" {
		out = append(out, prompt)
	}
	return out
}

// managedLaunchArgv and sandboxLaunchArgv are the two trusted/sandbox argv
// forms. Trusted launches force the shared `default` client profile; the
// sandbox strips the profile entirely (it owns its own fixed one).
func managedLaunchArgv(path string, forwarded []string, prompt string) []string {
	return forwardArgv(path, "default", forwarded, prompt)
}

func sandboxLaunchArgv(path string, forwarded []string, prompt string) []string {
	return forwardArgv(path, "", forwarded, prompt)
}

// generatedLaunchArgv prepends the one-shot generated --config, then forces the
// shared default client profile like every other trusted launch.
func generatedLaunchArgv(path, cfgPath string, forwarded []string, prompt string) []string {
	args := append([]string{"--config", cfgPath}, forwarded...)
	return forwardArgv(path, "default", args, prompt)
}

// runExec execs the launcher named by env (falling back to a bare command name
// on PATH), forwarding this process's args via argv and overlaying extraEnv (the
// vault broker environment) onto the inherited environment.
func runExec(env, fallback string, argv func(string, []string, string) []string, prompt string, extraEnv []string) {
	cmd := os.Getenv(env)
	if cmd == "" {
		cmd = fallback
	}
	path, err := exec.LookPath(cmd)
	if err != nil {
		fmt.Fprintln(os.Stderr, "code: not found:", err)
		os.Exit(1)
	}
	args := argv(path, os.Args[1:], prompt)
	if err := syscall.Exec(path, args, withBrokerEnv(os.Environ(), extraEnv)); err != nil {
		fmt.Fprintln(os.Stderr, "code: exec:", err)
		os.Exit(1)
	}
}

// launchGenerated writes the generated routing to a temp file and execs the
// managed omp wrapper with it as a single one-shot --config, on the shared
// default client profile with the selected vault's broker env. The wrapper
// supplies the platform extensions, managed defaults, and policy, so we must
// NOT re-layer defaults/policy here.
func launchGenerated(cfg, prompt string, extraEnv []string) {
	tmp, err := os.CreateTemp("", "code-gen-*.yml")
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	tmp.WriteString(cfg)
	tmp.Close()
	omp := os.Getenv("CODE_OMP")
	if omp == "" {
		omp = "omp"
	}
	path, err := exec.LookPath(omp)
	if err != nil {
		fmt.Fprintln(os.Stderr, "code: omp not found:", err)
		os.Exit(1)
	}
	args := generatedLaunchArgv(path, tmp.Name(), os.Args[1:], prompt)
	if err := syscall.Exec(path, args, withBrokerEnv(os.Environ(), extraEnv)); err != nil {
		fmt.Fprintln(os.Stderr, "code: exec:", err)
		os.Exit(1)
	}
}
