// code — the launcher picker + profile generator, as a Bubble Tea TUI.
//
// Manifest (generated by omp-configured, so this binary stays generic):
//
//	CODE_PROFILES  : TSV  name \t blurb \t detail \t group \t exe \t colorHex \t glyph
//	CODE_ROUTES    : routes.plain (managed profile routing blocks, keyed by name)
//	CODE_GENERATED : generated.plain (facet-grid blocks, keyed by combo id)
//	CODE_USAGE     : optional command (space-split) that prints `omp usage --json`
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"syscall"

	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// ── palette ──────────────────────────────────────────────────────────────────
const (
	cDim     = "#78829b"
	cGrp     = "#69727e"
	cAcc     = "#ff9f52"
	cBord    = "#3a4453"
	cHead    = "#9aa4b1"
	cSelBg   = "#1b212b"
	cGptSoft = "#6e91be"
	cClaSoft = "#c3a078"
	cRed     = "#d05c60"
	cGreen   = "#78c8aa"
)

var (
	stDim  = lipgloss.NewStyle().Foreground(lipgloss.Color(cDim))
	stGrp  = lipgloss.NewStyle().Foreground(lipgloss.Color(cGrp))
	stHead = lipgloss.NewStyle().Foreground(lipgloss.Color(cHead))
	stWarn = lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc))
	stBrk  = lipgloss.NewStyle().Foreground(lipgloss.Color(cRed))

	modelRe = regexp.MustCompile(`(gpt|claude)[A-Za-z0-9._-]*:(minimal|low|medium|high|xhigh|max)`)
	gptRe   = regexp.MustCompile(`\b(GPT|gpt|OpenAI|Codex|Spark|spark|Sol|Terra|Luna|Nano|nano)\b`)
	claRe   = regexp.MustCompile(`\b(Claude|claude|Anthropic|Opus|opus|Sonnet|sonnet|Haiku|haiku|Fable|fable)\b`)
)

// ── colourisers ──────────────────────────────────────────────────────────────
func lvl(s string) int {
	switch s {
	case "minimal":
		return 0
	case "low":
		return 1
	case "medium":
		return 2
	case "high":
		return 3
	case "xhigh":
		return 4
	}
	return 5
}

func shortModel(name string) string {
	if name == "gpt-5.4" {
		return name
	}
	p := strings.Split(name, "-")
	if strings.HasPrefix(name, "claude") && len(p) > 1 {
		return p[1]
	}
	return p[len(p)-1]
}

func clampByte(x float64) int {
	v := int(x)
	if v > 255 {
		return 255
	}
	if v < 0 {
		return 0
	}
	return v
}

func paintModel(tok string) string {
	i := strings.LastIndex(tok, ":")
	name, level := tok[:i], tok[i+1:]
	var br, bg, bb float64
	if strings.HasPrefix(tok, "gpt") {
		br, bg, bb = 110, 170, 240
	} else {
		br, bg, bb = 240, 160, 105
	}
	f := 0.60 + float64(lvl(level))*0.088
	col := lipgloss.Color(fmt.Sprintf("#%02x%02x%02x", clampByte(br*f), clampByte(bg*f), clampByte(bb*f)))
	return lipgloss.NewStyle().Foreground(col).Render(shortModel(name) + ":" + level)
}

func colorizeRoute(line string) string { return modelRe.ReplaceAllStringFunc(line, paintModel) }

// flavorize tints GPT-family words blue and Claude-family words orange over a
// dim base, with raw ANSI (keyword→colour→back to dim), like the gawk original.
const (
	ansiDim = "\x1b[38;2;120;130;145m"
	ansiGpt = "\x1b[38;2;110;145;190m"
	ansiCla = "\x1b[38;2;195;160;120m"
	ansiRst = "\x1b[0m"
)

func flavorize(s string) string {
	s = gptRe.ReplaceAllString(s, ansiGpt+"$1"+ansiDim)
	s = claRe.ReplaceAllString(s, ansiCla+"$1"+ansiDim)
	return ansiDim + s + ansiRst
}

// providerOf maps a short/long model name to its quota bucket.
func bucketOf(model string) string {
	m := model
	if i := strings.IndexByte(m, ':'); i >= 0 {
		m = m[:i]
	}
	switch {
	case strings.Contains(m, "fable"):
		return "claude-fable"
	case strings.Contains(m, "spark"):
		return "codex-spark"
	case strings.Contains(m, "claude"), strings.Contains(m, "sonnet"),
		strings.Contains(m, "haiku"), strings.Contains(m, "opus"):
		return "claude-main"
	}
	return "codex-main"
}

// ── data ─────────────────────────────────────────────────────────────────────
type profile struct {
	name, blurb, detail, group, exe, color, glyph string
}

func loadProfiles(path string) []profile {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	var out []profile
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1024*64), 1024*64)
	for sc.Scan() {
		p := strings.Split(sc.Text(), "\t")
		for len(p) < 7 {
			p = append(p, "")
		}
		out = append(out, profile{p[0], p[1], p[2], p[3], p[4], p[5], p[6]})
	}
	return out
}

// loadBlocks parses a routes/generated page into name -> role rows.
func loadBlocks(path string) map[string][]string {
	blocks := map[string][]string{}
	f, err := os.Open(path)
	if err != nil {
		return blocks
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1024*128), 1024*128)
	var cur string
	for sc.Scan() {
		line := sc.Text()
		if line == "" {
			cur = ""
			continue
		}
		if line[0] != ' ' {
			if fs := strings.Fields(line); len(fs) > 0 {
				cur = fs[0]
				blocks[cur] = nil
			}
			continue
		}
		if cur != "" {
			blocks[cur] = append(blocks[cur], line)
		}
	}
	return blocks
}

// ── usage + availability ─────────────────────────────────────────────────────
type usageWin struct {
	label string
	pct   int
	tier  string
	secs  int64
	prov  string
}

type availability struct {
	bucket map[string]string // bucket -> "ok" | "maxed" | "unauthed"
	reset  map[string]int64
	wins   []usageWin
	ok     bool
}

func loadAvailability(cmd string) availability {
	a := availability{bucket: map[string]string{}, reset: map[string]int64{}}
	if cmd == "" {
		return a
	}
	parts := strings.Fields(cmd)
	out, err := exec.Command(parts[0], parts[1:]...).Output()
	if err != nil || len(out) == 0 {
		return a
	}
	var doc struct {
		Reports []struct {
			Provider string `json:"provider"`
			Limits   []struct {
				Label string `json:"label"`
				Scope struct {
					Tier string `json:"tier"`
				} `json:"scope"`
				Amount struct {
					UsedFraction float64 `json:"usedFraction"`
				} `json:"amount"`
				Window struct {
					ResetsAt   int64 `json:"resetsAt"`
					DurationMs int64 `json:"durationMs"`
				} `json:"window"`
			} `json:"limits"`
		} `json:"reports"`
	}
	if json.Unmarshal(out, &doc) != nil {
		return a
	}
	a.ok = true
	provSeen := map[string]bool{}
	// nowMs approximated from the soonest resetsAt is unreliable; use max pct only.
	for _, r := range doc.Reports {
		provSeen[r.Provider] = true
		for _, l := range r.Limits {
			pct := int(l.Amount.UsedFraction*100 + 0.5)
			a.wins = append(a.wins, usageWin{l.Label, pct, l.Scope.Tier, l.Window.ResetsAt / 1000, r.Provider})
			bkt := bucketForProviderTier(r.Provider, l.Scope.Tier)
			if bkt == "" {
				continue
			}
			if pct >= 100 {
				a.bucket[bkt] = "maxed"
				a.reset[bkt] = l.Window.ResetsAt / 1000
			} else if a.bucket[bkt] != "maxed" {
				a.bucket[bkt] = "ok"
			}
		}
	}
	for _, b := range []string{"codex-main", "codex-spark", "claude-main", "claude-fable"} {
		p := "openai-codex"
		if strings.HasPrefix(b, "claude") {
			p = "anthropic"
		}
		if !provSeen[p] {
			a.bucket[b] = "unauthed"
		} else if _, ok := a.bucket[b]; !ok {
			a.bucket[b] = "ok"
		}
	}
	return a
}

func bucketForProviderTier(prov, tier string) string {
	if prov == "openai-codex" {
		if tier == "spark" {
			return "codex-spark"
		}
		if tier == "" || tier == "-" {
			return "codex-main"
		}
	}
	if prov == "anthropic" {
		if tier == "fable" {
			return "claude-fable"
		}
		if tier == "" || tier == "-" {
			return "claude-main"
		}
	}
	return ""
}

func (a availability) down(bucket string) bool {
	return a.bucket[bucket] == "maxed" || a.bucket[bucket] == "unauthed"
}

func fmtSecs(s int64) string {
	if s <= 0 {
		return "now"
	}
	switch {
	case s >= 86400:
		return fmt.Sprintf("%dd", s/86400)
	case s >= 3600:
		return fmt.Sprintf("%dh", s/3600)
	case s >= 60:
		return fmt.Sprintf("%dm", s/60)
	}
	return fmt.Sprintf("%ds", s)
}

func (a availability) note() string {
	label := map[string]string{"codex-main": "Codex", "codex-spark": "Spark", "claude-main": "Claude", "claude-fable": "Fable"}
	seen := map[string]bool{}
	var parts []string
	for _, b := range []string{"codex-main", "codex-spark", "claude-main", "claude-fable"} {
		if !a.down(b) {
			continue
		}
		var n string
		if a.bucket[b] == "maxed" {
			n = fmt.Sprintf("%s maxed · %s", label[b], fmtSecs(a.reset[b]))
		} else if strings.HasPrefix(b, "codex") {
			n = "needs Codex"
		} else {
			n = "needs Claude"
		}
		if !seen[n] {
			seen[n] = true
			parts = append(parts, n)
		}
	}
	return strings.Join(parts, " · ")
}

var substRoles = map[string]bool{"default": true, "task": true, "plan": true, "slow": true, "designer": true, "reviewer": true, "librarian": true}

// impact: "" (ok) | "degraded" | "broken", from a profile's routing block.
func (a availability) impact(rows []string) string {
	if !a.ok {
		return ""
	}
	defaultRunnable, defaultSeen, anyLeadDown := false, false, false
	for _, row := range rows {
		fields := strings.Fields(strings.TrimSpace(strings.ReplaceAll(row, "→", " ")))
		if len(fields) == 0 {
			continue
		}
		i := 0
		if fields[0] == "●" {
			i = 1
		}
		if i >= len(fields) {
			continue
		}
		role := fields[i]
		var models []string
		for _, f := range fields[i+1:] {
			if modelRe.MatchString(f) {
				models = append(models, f)
			}
		}
		if len(models) == 0 {
			continue
		}
		if substRoles[role] && a.down(bucketOf(models[0])) {
			anyLeadDown = true
		}
		if role == "default" {
			defaultSeen = true
			for _, m := range models {
				if !a.down(bucketOf(m)) {
					defaultRunnable = true
				}
			}
		}
	}
	if defaultSeen && !defaultRunnable {
		return "broken"
	}
	if anyLeadDown {
		return "degraded"
	}
	return ""
}

// ── routing render (depth: 0 lead · 1 full) ──────────────────────────────────
func renderRoute(rows []string, depth int) string {
	var b strings.Builder
	for _, r := range rows {
		line := r
		if depth == 0 {
			// keep only the primary (drop the fallback chain)
			if i := strings.Index(line, "→"); i >= 0 {
				line = strings.TrimRight(line[:i], " ")
			}
		}
		b.WriteString(colorizeRoute(line) + "\n")
	}
	return b.String()
}

// ── generator facets ─────────────────────────────────────────────────────────
type facet struct {
	key    string
	values []string
	glyph  string
}

func facetDefs(glyphs map[string]string) []facet {
	return []facet{
		{"lane", []string{"gpt-only", "gpt-led", "mixed", "claude-led", "claude-only"}, glyphs["lane"]},
		{"model", []string{"fast", "normal", "smart"}, glyphs["model"]},
		{"thinking", []string{"low", "medium", "high", "xhigh"}, glyphs["thinking"]},
		{"spark", []string{"on", "off"}, glyphs["spark"]},
		{"fable", []string{"on", "off"}, glyphs["fable"]},
	}
}

func comboID(sel map[string]string) string {
	lane := sel["lane"]
	sp, fb := sel["spark"], sel["fable"]
	if lane == "gpt-only" {
		fb = "off"
	}
	if lane == "claude-only" {
		sp = "off"
	}
	spid, faid := "nosp", "nofa"
	if sp == "on" {
		spid = "sp"
	}
	if fb == "on" {
		faid = "fa"
	}
	return fmt.Sprintf("%s_%s_%s_%s_%s", lane, sel["model"], sel["thinking"], spid, faid)
}

func laneColor(lane string) string {
	switch lane {
	case "gpt-only", "gpt-led":
		return "#62a7ff"
	case "mixed":
		return "#aa96e1"
	}
	return "#ff9f52"
}

// ── model ────────────────────────────────────────────────────────────────────
type viewKind int

const (
	pickerView viewKind = iota
	genView
)

type model struct {
	profiles  []profile
	routes    map[string][]string
	generated map[string][]string
	avail     availability
	glyphs    map[string]string

	view     viewKind
	cursor   int
	depth    int // 0 lead · 1 full
	collapse bool

	facets []facet
	fcur   int
	sel    map[string]string

	vp   viewport.Model
	w, h int
	rdy  bool

	chosen string
}

func (m model) Init() tea.Cmd { return nil }

func (m model) listW() int {
	if m.collapse {
		return m.w
	}
	if m.w < 96 {
		return m.w / 3
	}
	return 42
}

func (m *model) usageBar() string {
	if !m.avail.ok || len(m.avail.wins) == 0 {
		return ""
	}
	var parts []string
	for _, wdw := range m.avail.wins {
		if wdw.pct < 0 {
			continue
		}
		filled := wdw.pct / 10
		if filled > 10 {
			filled = 10
		}
		bar := strings.Repeat("█", filled) + strings.Repeat("░", 10-filled)
		col := cGreen
		if wdw.pct >= 100 {
			col = cRed
		} else if wdw.pct >= 80 {
			col = cAcc
		}
		seg := lipgloss.NewStyle().Foreground(lipgloss.Color(col)).Render(bar) +
			stDim.Render(fmt.Sprintf(" %s %d%%", wdw.label, wdw.pct))
		parts = append(parts, seg)
	}
	return stDim.Render("  usage  ") + strings.Join(parts, stDim.Render("   "))
}

func (m *model) syncPreview() {
	if !m.rdy || m.collapse {
		return
	}
	var b strings.Builder
	if m.view == pickerView {
		p := m.profiles[m.cursor]
		nm := lipgloss.NewStyle().Foreground(lipgloss.Color(p.color)).Bold(true).Render(p.name)
		b.WriteString(nm + "  " + flavorize(p.blurb) + "\n\n")
		b.WriteString(flavorize(p.detail) + "\n")
		if imp := m.avail.impact(m.routes[p.name]); imp != "" {
			b.WriteString("\n")
			if imp == "broken" {
				b.WriteString(stBrk.Render("✗ "+m.avail.note()+" — default has no live fallback") + "\n")
			} else {
				b.WriteString(stWarn.Render("⚠ "+m.avail.note()+" — runs on a fallback") + "\n")
			}
		}
		b.WriteString("\n" + stDim.Render("── routing ─────────────────") + "\n")
		b.WriteString(renderRoute(m.routes[p.name], m.depth))
	} else {
		id := comboID(m.sel)
		b.WriteString(lipgloss.NewStyle().Bold(true).Render("generated profile") + "\n")
		b.WriteString(stDim.Render(strings.ReplaceAll(id, "_", " ")) + "\n\n")
		if rows, ok := m.generated[id]; ok {
			b.WriteString(stDim.Render("── routing ─────────────────") + "\n")
			b.WriteString(renderRoute(rows, m.depth))
		} else {
			b.WriteString(stDim.Render("no profile for this combination") + "\n")
		}
	}
	// wrap to pane width so a long chain can never shift the layout.
	content := lipgloss.NewStyle().Width(m.vp.Width).Render(b.String())
	m.vp.SetContent(content)
	m.vp.GotoTop()
}

func (m *model) relayout() {
	pw := m.w - m.listW() - 3
	if pw < 10 {
		pw = 10
	}
	vh := m.h - 3
	if vh < 3 {
		vh = 3
	}
	if !m.rdy {
		m.vp = viewport.New(pw, vh)
		m.rdy = true
	} else {
		m.vp.Width, m.vp.Height = pw, vh
	}
	m.syncPreview()
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.w, m.h = msg.Width, msg.Height
		m.relayout()
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "esc", "ctrl+c":
			return m, tea.Quit
		case "tab":
			if m.view == pickerView {
				m.view = genView
			} else {
				m.view = pickerView
			}
			m.syncPreview()
		case "p":
			m.collapse = !m.collapse
			m.relayout()
		case "f":
			m.depth = (m.depth + 1) % 2
			m.syncPreview()
		case "up", "k":
			m.moveUp()
		case "down", "j":
			m.moveDown()
		case "left", "h":
			if m.view == genView {
				m.cycleFacet(-1)
			}
		case "right", "l":
			if m.view == genView {
				m.cycleFacet(1)
			}
		case "enter":
			if m.view == pickerView {
				m.chosen = m.profiles[m.cursor].exe
				return m, tea.Quit
			}
		}
	case tea.MouseMsg:
		switch msg.Button {
		case tea.MouseButtonWheelUp:
			m.vp.LineUp(3)
		case tea.MouseButtonWheelDown:
			m.vp.LineDown(3)
		}
	}
	return m, nil
}

func (m *model) moveUp() {
	if m.view == pickerView {
		if m.cursor > 0 {
			m.cursor--
			m.syncPreview()
		}
	} else if m.fcur > 0 {
		m.fcur--
	}
}
func (m *model) moveDown() {
	if m.view == pickerView {
		if m.cursor < len(m.profiles)-1 {
			m.cursor++
			m.syncPreview()
		}
	} else if m.fcur < len(m.facets)-1 {
		m.fcur++
	}
}
func (m *model) cycleFacet(dir int) {
	f := m.facets[m.fcur]
	cur := m.sel[f.key]
	idx := 0
	for i, v := range f.values {
		if v == cur {
			idx = i
		}
	}
	idx = (idx + dir + len(f.values)) % len(f.values)
	m.sel[f.key] = f.values[idx]
	m.syncPreview()
}

func (m model) View() string {
	if !m.rdy {
		return "loading…"
	}
	var left string
	if m.view == pickerView {
		left = m.pickerList()
	} else {
		left = m.genList()
	}
	var body string
	if m.collapse {
		body = left
	} else {
		right := lipgloss.NewStyle().
			Border(lipgloss.NormalBorder(), false, false, false, true).
			BorderForeground(lipgloss.Color(cBord)).PaddingLeft(2).
			Width(m.w - m.listW() - 3).Height(m.h - 3).
			Render(m.vp.View())
		body = lipgloss.JoinHorizontal(lipgloss.Top, lipgloss.NewStyle().Width(m.listW()).Render(left), right)
	}
	tabP, tabG := stDim.Render("profiles"), stDim.Render("generator")
	if m.view == pickerView {
		tabP = lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc)).Bold(true).Render("profiles")
	} else {
		tabG = lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc)).Bold(true).Render("generator")
	}
	head := "  " + tabP + stDim.Render(" · ") + tabG +
		stDim.Render("    tab switch · f depth · p collapse · enter launch · q quit")
	foot := m.usageBar()
	out := head + "\n" + body
	if foot != "" {
		out += "\n" + foot
	}
	return out
}

func (m model) pickerList() string {
	trunc := lipgloss.NewStyle().MaxWidth(m.listW()).Inline(true)
	var b strings.Builder
	lastGroup := ""
	for i, p := range m.profiles {
		if p.group != lastGroup {
			b.WriteString(stGrp.Render(p.group) + "\n")
			lastGroup = p.group
		}
		mark := "  "
		switch m.avail.impact(m.routes[p.name]) {
		case "broken":
			mark = stBrk.Render("✗ ")
		case "degraded":
			mark = stWarn.Render("⚠ ")
		}
		gly := lipgloss.NewStyle().Foreground(lipgloss.Color(p.color)).Render(p.glyph)
		nm := lipgloss.NewStyle().Foreground(lipgloss.Color(p.color)).Bold(true).Render(p.name)
		row := fmt.Sprintf("%s%s %-6s %s", mark, gly, nm, flavorize(p.blurb))
		row = trunc.Render(row)
		if i == m.cursor {
			row = lipgloss.NewStyle().Background(lipgloss.Color(cSelBg)).Width(m.listW()).Render(row)
		}
		b.WriteString(row + "\n")
	}
	return b.String()
}

func (m model) genList() string {
	var b strings.Builder
	b.WriteString(stGrp.Render("build a profile") + "\n\n")
	for i, f := range m.facets {
		na := (f.key == "fable" && m.sel["lane"] == "gpt-only") || (f.key == "spark" && m.sel["lane"] == "claude-only")
		gly := lipgloss.NewStyle().Foreground(lipgloss.Color(laneColor(m.sel["lane"]))).Render(f.glyph)
		row := fmt.Sprintf(" %s %s%-9s", gly, stDim.Render(""), pad(f.key, 9))
		for _, v := range f.values {
			switch {
			case na:
				row += "   " + stDim.Render(v)
			case v == m.sel[f.key]:
				col := cAcc
				if f.key == "lane" {
					col = laneColor(v)
				} else if (f.key == "spark" || f.key == "fable") && v == "on" {
					col = cGreen
				}
				row += "  " + lipgloss.NewStyle().Foreground(lipgloss.Color(col)).Bold(true).Render("["+v+"]")
			default:
				row += "   " + stDim.Render(v)
			}
		}
		if na {
			row += "   " + stDim.Render("— n/a for this lane")
		}
		if i == m.fcur {
			row = lipgloss.NewStyle().Background(lipgloss.Color(cSelBg)).Render(row)
		}
		b.WriteString(row + "\n")
	}
	return b.String()
}

func pad(s string, n int) string {
	for len(s) < n {
		s += " "
	}
	return s
}

func main() {
	profiles := loadProfiles(os.Getenv("CODE_PROFILES"))
	if len(profiles) == 0 {
		fmt.Fprintln(os.Stderr, "code: no profiles (CODE_PROFILES)")
		os.Exit(2)
	}
	glyphs := map[string]string{}
	for _, kv := range strings.Split(os.Getenv("CODE_FACET_GLYPHS"), ",") {
		if p := strings.SplitN(kv, "=", 2); len(p) == 2 {
			glyphs[p[0]] = p[1]
		}
	}
	m := model{
		profiles:  profiles,
		routes:    loadBlocks(os.Getenv("CODE_ROUTES")),
		generated: loadBlocks(os.Getenv("CODE_GENERATED")),
		avail:     loadAvailability(os.Getenv("CODE_USAGE")),
		glyphs:    glyphs,
		facets:    facetDefs(glyphs),
		sel:       map[string]string{"lane": "mixed", "model": "normal", "thinking": "medium", "spark": "on", "fable": "off"},
	}
	final, err := tea.NewProgram(m, tea.WithAltScreen(), tea.WithMouseCellMotion()).Run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	if fm, ok := final.(model); ok && fm.chosen != "" {
		args := append([]string{fm.chosen}, os.Args[1:]...)
		if err := syscall.Exec(fm.chosen, args, os.Environ()); err != nil {
			fmt.Fprintln(os.Stderr, "code: exec:", err)
			os.Exit(1)
		}
	}
}
