// code — the launcher picker + profile generator, as a Bubble Tea TUI.
//
// Manifest (generated by omp-configured, so this binary stays generic):
//
//	CODE_PROFILES  : TSV  name \t blurb \t detail \t group \t exe \t colorHex \t glyph
//	CODE_ROUTES    : routes.plain (managed profile routing blocks, keyed by name)
//	CODE_GENERATED : generated.plain (facet-grid blocks, keyed by combo id)
//	CODE_USAGE     : optional command (space-split) that prints `omp usage --json`
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"time"

	"github.com/charmbracelet/bubbles/spinner"
	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// ── palette ──────────────────────────────────────────────────────────────────
const (
	cDim     = "#78829b"
	cGrp     = "#69727e"
	cAcc     = "#ff9f52"
	cBord    = "#3a4453"
	cHead    = "#9aa4b1"
	cSelBg   = "#1b212b"
	cGptSoft = "#6e91be"
	cClaSoft = "#c3a078"
	cRed     = "#d05c60"
	cGreen   = "#78c8aa"
)

var (
	stDim  = lipgloss.NewStyle().Foreground(lipgloss.Color(cDim))
	stGrp  = lipgloss.NewStyle().Foreground(lipgloss.Color(cGrp))
	stHead = lipgloss.NewStyle().Foreground(lipgloss.Color(cHead))
	stWarn = lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc))
	stBrk  = lipgloss.NewStyle().Foreground(lipgloss.Color(cRed))

	modelRe = regexp.MustCompile(`(gpt|claude)[A-Za-z0-9._-]*:(minimal|low|medium|high|xhigh|max)`)
	gptRe   = regexp.MustCompile(`\b(GPT|gpt|OpenAI|Codex|Spark|spark|Sol|Terra|Luna|Nano|nano)\b`)
	claRe   = regexp.MustCompile(`\b(Claude|claude|Anthropic|Opus|opus|Sonnet|sonnet|Haiku|haiku|Fable|fable)\b`)
)

// ── colourisers ──────────────────────────────────────────────────────────────
func lvl(s string) int {
	switch s {
	case "minimal":
		return 0
	case "low":
		return 1
	case "medium":
		return 2
	case "high":
		return 3
	case "xhigh":
		return 4
	}
	return 5
}

func shortModel(name string) string {
	if name == "gpt-5.4" {
		return name
	}
	p := strings.Split(name, "-")
	if strings.HasPrefix(name, "claude") && len(p) > 1 {
		return p[1]
	}
	return p[len(p)-1]
}

func clampByte(x float64) int {
	v := int(x)
	if v > 255 {
		return 255
	}
	if v < 0 {
		return 0
	}
	return v
}

func paintModel(tok string) string {
	i := strings.LastIndex(tok, ":")
	name, level := tok[:i], tok[i+1:]
	var br, bg, bb float64
	if strings.HasPrefix(tok, "gpt") {
		br, bg, bb = 110, 170, 240
	} else {
		br, bg, bb = 240, 160, 105
	}
	f := 0.60 + float64(lvl(level))*0.088
	col := lipgloss.Color(fmt.Sprintf("#%02x%02x%02x", clampByte(br*f), clampByte(bg*f), clampByte(bb*f)))
	return lipgloss.NewStyle().Foreground(col).Render(shortModel(name) + ":" + level)
}

func colorizeRoute(line string) string { return modelRe.ReplaceAllStringFunc(line, paintModel) }

// flavorize tints GPT-family words blue and Claude-family words orange over a
// dim base, with raw ANSI (keyword→colour→back to dim), like the gawk original.
const (
	ansiDim = "\x1b[38;2;120;130;145m"
	ansiGpt = "\x1b[38;2;110;145;190m"
	ansiCla = "\x1b[38;2;195;160;120m"
	ansiRst = "\x1b[0m"
)

func flavorize(s string) string {
	s = gptRe.ReplaceAllString(s, ansiGpt+"$1"+ansiDim)
	s = claRe.ReplaceAllString(s, ansiCla+"$1"+ansiDim)
	return ansiDim + s + ansiRst
}

// providerOf maps a short/long model name to its quota bucket.
func bucketOf(model string) string {
	m := model
	if i := strings.IndexByte(m, ':'); i >= 0 {
		m = m[:i]
	}
	switch {
	case strings.Contains(m, "fable"):
		return "claude-fable"
	case strings.Contains(m, "spark"):
		return "codex-spark"
	case strings.Contains(m, "claude"), strings.Contains(m, "sonnet"),
		strings.Contains(m, "haiku"), strings.Contains(m, "opus"):
		return "claude-main"
	}
	return "codex-main"
}

// ── data ─────────────────────────────────────────────────────────────────────
type profile struct {
	name, blurb, detail, group, exe, color, glyph string
}

func loadProfiles(path string) []profile {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	var out []profile
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1024*64), 1024*64)
	for sc.Scan() {
		p := strings.Split(sc.Text(), "\t")
		for len(p) < 7 {
			p = append(p, "")
		}
		out = append(out, profile{p[0], p[1], p[2], p[3], p[4], p[5], p[6]})
	}
	return out
}

// loadBlocks parses a routes/generated page into name -> role rows.
func loadBlocks(path string) map[string][]string {
	blocks := map[string][]string{}
	f, err := os.Open(path)
	if err != nil {
		return blocks
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1024*128), 1024*128)
	var cur string
	for sc.Scan() {
		line := sc.Text()
		if line == "" {
			cur = ""
			continue
		}
		if line[0] != ' ' {
			if fs := strings.Fields(line); len(fs) > 0 {
				cur = fs[0]
				blocks[cur] = nil
			}
			continue
		}
		if cur != "" {
			blocks[cur] = append(blocks[cur], line)
		}
	}
	return blocks
}

// ── usage + availability ─────────────────────────────────────────────────────
type usageWin struct {
	label string
	pct   int
	tier  string
	secs  int64 // seconds until reset (relative)
	dur   int64 // window length in seconds
	prov  string
}

type availability struct {
	bucket map[string]string // bucket -> "ok" | "maxed" | "unauthed"
	reset  map[string]int64
	wins   []usageWin
	ok     bool
}

func loadAvailability(cmd string) availability {
	a := availability{bucket: map[string]string{}, reset: map[string]int64{}}
	if cmd == "" {
		return a
	}
	parts := strings.Fields(cmd)
	out, err := exec.Command(parts[0], parts[1:]...).Output()
	if err != nil || len(out) == 0 {
		return a
	}
	var doc struct {
		Reports []struct {
			Provider string `json:"provider"`
			Limits   []struct {
				Label string `json:"label"`
				Scope struct {
					Tier string `json:"tier"`
				} `json:"scope"`
				Amount struct {
					UsedFraction float64 `json:"usedFraction"`
				} `json:"amount"`
				Window struct {
					ResetsAt   int64 `json:"resetsAt"`
					DurationMs int64 `json:"durationMs"`
				} `json:"window"`
			} `json:"limits"`
		} `json:"reports"`
	}
	if json.Unmarshal(out, &doc) != nil {
		return a
	}
	a.ok = true
	provSeen := map[string]bool{}
	now := time.Now().Unix()
	for _, r := range doc.Reports {
		provSeen[r.Provider] = true
		for _, l := range r.Limits {
			pct := int(l.Amount.UsedFraction*100 + 0.5)
			a.wins = append(a.wins, usageWin{l.Label, pct, l.Scope.Tier, l.Window.ResetsAt/1000 - now, l.Window.DurationMs / 1000, r.Provider})
			bkt := bucketForProviderTier(r.Provider, l.Scope.Tier)
			if bkt == "" {
				continue
			}
			if pct >= 100 {
				a.bucket[bkt] = "maxed"
				a.reset[bkt] = l.Window.ResetsAt / 1000
			} else if a.bucket[bkt] != "maxed" {
				a.bucket[bkt] = "ok"
			}
		}
	}
	for _, b := range []string{"codex-main", "codex-spark", "claude-main", "claude-fable"} {
		p := "openai-codex"
		if strings.HasPrefix(b, "claude") {
			p = "anthropic"
		}
		if !provSeen[p] {
			a.bucket[b] = "unauthed"
		} else if _, ok := a.bucket[b]; !ok {
			a.bucket[b] = "ok"
		}
	}
	return a
}

func bucketForProviderTier(prov, tier string) string {
	if prov == "openai-codex" {
		if tier == "spark" {
			return "codex-spark"
		}
		if tier == "" || tier == "-" {
			return "codex-main"
		}
	}
	if prov == "anthropic" {
		if tier == "fable" {
			return "claude-fable"
		}
		if tier == "" || tier == "-" {
			return "claude-main"
		}
	}
	return ""
}

func (a availability) down(bucket string) bool {
	return a.bucket[bucket] == "maxed" || a.bucket[bucket] == "unauthed"
}

func fmtSecs(s int64) string {
	if s <= 0 {
		return "now"
	}
	switch {
	case s >= 86400:
		return fmt.Sprintf("%dd", s/86400)
	case s >= 3600:
		return fmt.Sprintf("%dh", s/3600)
	case s >= 60:
		return fmt.Sprintf("%dm", s/60)
	}
	return fmt.Sprintf("%ds", s)
}

func (a availability) note() string {
	label := map[string]string{"codex-main": "Codex", "codex-spark": "Spark", "claude-main": "Claude", "claude-fable": "Fable"}
	seen := map[string]bool{}
	var parts []string
	for _, b := range []string{"codex-main", "codex-spark", "claude-main", "claude-fable"} {
		if !a.down(b) {
			continue
		}
		var n string
		if a.bucket[b] == "maxed" {
			n = fmt.Sprintf("%s maxed · %s", label[b], fmtSecs(a.reset[b]))
		} else if strings.HasPrefix(b, "codex") {
			n = "needs Codex"
		} else {
			n = "needs Claude"
		}
		if !seen[n] {
			seen[n] = true
			parts = append(parts, n)
		}
	}
	return strings.Join(parts, " · ")
}

var substRoles = map[string]bool{"default": true, "task": true, "plan": true, "slow": true, "designer": true, "reviewer": true, "librarian": true}

// impact: "" (ok) | "degraded" | "broken", from a profile's routing block.
func (a availability) impact(rows []string) string {
	if !a.ok {
		return ""
	}
	defaultRunnable, defaultSeen, anyLeadDown := false, false, false
	for _, row := range rows {
		fields := strings.Fields(strings.TrimSpace(strings.ReplaceAll(row, "→", " ")))
		if len(fields) == 0 {
			continue
		}
		i := 0
		if fields[0] == "●" {
			i = 1
		}
		if i >= len(fields) {
			continue
		}
		role := fields[i]
		var models []string
		for _, f := range fields[i+1:] {
			if modelRe.MatchString(f) {
				models = append(models, f)
			}
		}
		if len(models) == 0 {
			continue
		}
		if substRoles[role] && a.down(bucketOf(models[0])) {
			anyLeadDown = true
		}
		if role == "default" {
			defaultSeen = true
			for _, m := range models {
				if !a.down(bucketOf(m)) {
					defaultRunnable = true
				}
			}
		}
	}
	if defaultSeen && !defaultRunnable {
		return "broken"
	}
	if anyLeadDown {
		return "degraded"
	}
	return ""
}

// ── routing render (depth: 0 lead · 1 full) ──────────────────────────────────
func renderRoute(rows []string, depth int) string {
	var b strings.Builder
	for _, r := range rows {
		line := r
		if depth == 0 {
			// keep only the primary (drop the fallback chain)
			if i := strings.Index(line, "→"); i >= 0 {
				line = strings.TrimRight(line[:i], " ")
			}
		}
		b.WriteString(colorizeRoute(line) + "\n")
	}
	return b.String()
}

// ── generator facets ─────────────────────────────────────────────────────────
type facet struct {
	key    string
	values []string
	glyph  string
}

func facetDefs(glyphs map[string]string) []facet {
	return []facet{
		{"lane", []string{"gpt-only", "gpt-led", "mixed", "claude-led", "claude-only"}, glyphs["lane"]},
		{"model", []string{"fast", "normal", "smart"}, glyphs["model"]},
		{"thinking", []string{"low", "medium", "high", "xhigh"}, glyphs["thinking"]},
		{"spark", []string{"on", "off"}, glyphs["spark"]},
		{"fable", []string{"on", "off"}, glyphs["fable"]},
	}
}

func comboID(sel map[string]string) string {
	lane := sel["lane"]
	sp, fb := sel["spark"], sel["fable"]
	if lane == "gpt-only" {
		fb = "off"
	}
	if lane == "claude-only" {
		sp = "off"
	}
	spid, faid := "nosp", "nofa"
	if sp == "on" {
		spid = "sp"
	}
	if fb == "on" {
		faid = "fa"
	}
	return fmt.Sprintf("%s_%s_%s_%s_%s", lane, sel["model"], sel["thinking"], spid, faid)
}

func laneColor(lane string) string {
	switch lane {
	case "gpt-only", "gpt-led":
		return "#62a7ff"
	case "mixed":
		return "#aa96e1"
	}
	return "#ff9f52"
}

// ── model ────────────────────────────────────────────────────────────────────
type viewKind int

const (
	pickerView viewKind = iota
	genView
)

// layout modes, chosen from the terminal size (unless the user collapses):
//
//	stacked   — wide+tall: generator on top, profiles below, preview on the right
//	split     — medium:    the focused list on the left, preview on the right
//	collapsed — narrow/‹p›: one full-width pane (list, or the result with showResult)
const (
	modeStacked = iota
	modeSplit
	modeCollapsed
)

// genRowWidth is the width needed to render the widest generator facet row (all
// options) on a single line — the minimum for the left panel.
func (m model) genRowWidth() int {
	max := 30
	for _, f := range m.facets {
		w := 14 // ▸ + glyph + spaces + padded label
		for _, v := range f.values {
			w += len(v) + 4
		}
		if w > max {
			max = w
		}
	}
	return max + 2
}

func (m model) mode() int {
	if m.collapse {
		return modeCollapsed
	}
	if m.w < m.genRowWidth()+33 { // no room for the gen list + a useful preview
		return modeCollapsed
	}
	if m.h >= 34 {
		return modeStacked
	}
	return modeSplit
}

type model struct {
	profiles  []profile
	routes    map[string][]string
	generated map[string][]string
	avail     availability
	glyphs    map[string]string

	view       viewKind
	cursor     int
	depth      int // 0 lead · 1 full
	collapse   bool
	showResult bool // in collapsed mode: show the preview full-width

	facets []facet
	fcur   int
	sel    map[string]string

	vp       viewport.Model
	spin     spinner.Model
	w, h     int
	rdy      bool
	usageCmd string

	chosen string
}

// usageMsg carries availability fetched off the main thread so startup never
// blocks on `omp usage --json` (a network call).
type usageMsg availability

func fetchUsageCmd(cmd string) tea.Cmd {
	if cmd == "" {
		return nil
	}
	return func() tea.Msg { return usageMsg(loadAvailability(cmd)) }
}

func (m model) Init() tea.Cmd { return tea.Batch(fetchUsageCmd(m.usageCmd), m.spin.Tick) }

func (m model) listW() int {
	// wide enough for the generator options on one line; capped so a very wide
	// terminal doesn't stretch the list needlessly.
	w := m.genRowWidth()
	if w > m.w-33 {
		w = m.w - 33
	}
	if w > 80 {
		w = 80
	}
	return w
}

// gradient bar (green→red), 10 cells, matching the fzf panel.
func barStr(p int) string {
	var r, g float64
	if p <= 50 {
		r, g = 90+float64(p)*3, 200
	} else {
		r, g = 235, 200-float64(p-50)*3
	}
	if r > 235 {
		r = 235
	}
	if g < 60 {
		g = 60
	}
	fill := (p*10 + 50) / 100
	if fill > 10 {
		fill = 10
	}
	if fill < 0 {
		fill = 0
	}
	filled := lipgloss.NewStyle().Foreground(lipgloss.Color(fmt.Sprintf("#%02x%02x46", clampByte(r), clampByte(g)))).Render(strings.Repeat("█", fill))
	return filled + stDim.Render(strings.Repeat("░", 10-fill))
}

func fmtReset(s int64) string {
	if s < 0 {
		s = 0
	}
	switch {
	case s >= 86400:
		return fmt.Sprintf("%dd%dh", s/86400, (s%86400)/3600)
	case s >= 3600:
		return fmt.Sprintf("%dh%dm", s/3600, (s%3600)/60)
	}
	return fmt.Sprintf("%dm", s/60)
}

func shortWin(l string) string {
	switch l {
	case "5 hours", "Claude 5 Hour":
		return "5h"
	case "7 days", "Claude 7 Day":
		return "7d"
	case "5 hours (Spark)":
		return "5h spark"
	case "7 days (Spark)":
		return "7d spark"
	case "Claude 7 Day (Fable)":
		return "7d fable"
	}
	return l
}

func (m *model) usagePanel() string {
	if !m.avail.ok {
		if m.usageCmd != "" {
			return stDim.Render("  " + m.spin.View() + " fetching usage…")
		}
		return ""
	}
	if len(m.avail.wins) == 0 {
		return ""
	}
	wins := append([]usageWin(nil), m.avail.wins...)
	provOrder := func(p string) int {
		switch p {
		case "openai-codex":
			return 0
		case "anthropic":
			return 1
		}
		return 2
	}
	tierOrder := func(t string) int {
		if t == "" || t == "-" {
			return 0
		}
		return 1
	}
	sort.SliceStable(wins, func(i, j int) bool {
		if o := provOrder(wins[i].prov) - provOrder(wins[j].prov); o != 0 {
			return o < 0
		}
		if o := tierOrder(wins[i].tier) - tierOrder(wins[j].tier); o != 0 {
			return o < 0
		}
		return wins[i].dur < wins[j].dur
	})
	blocks := map[string][]string{}
	var order []string
	for _, w := range wins {
		if _, ok := blocks[w.prov]; !ok {
			order = append(order, w.prov)
			pcol, pname := "#62a7ff", "Codex"
			if w.prov == "anthropic" {
				pcol, pname = "#ff9f52", "Claude"
			}
			blocks[w.prov] = []string{lipgloss.NewStyle().Foreground(lipgloss.Color(pcol)).Bold(true).Render(pname)}
		}
		blocks[w.prov] = append(blocks[w.prov], m.usageRow(w))
	}
	// side-by-side when there's horizontal room, else stacked.
	const colW = 46
	if len(order) > 1 && m.w >= colW*len(order) {
		var cols []string
		for _, p := range order {
			cols = append(cols, lipgloss.NewStyle().Width(colW).Render(strings.Join(blocks[p], "\n")))
		}
		return lipgloss.JoinHorizontal(lipgloss.Top, cols...)
	}
	var lines []string
	for _, p := range order {
		lines = append(lines, blocks[p]...)
	}
	return strings.Join(lines, "\n")
}

func (m *model) usageRow(w usageWin) string {
	note := ""
	if w.pct >= 80 {
		note = "  " + stWarn.Render("tight")
	}
	if w.tier == "spark" && w.pct == 0 {
		note = "  " + lipgloss.NewStyle().Foreground(lipgloss.Color(cGreen)).Render("idle")
	}
	reset := stDim.Render("↻" + fmtReset(w.secs))
	if w.dur > 0 && w.secs*10 < w.dur {
		reset = lipgloss.NewStyle().Foreground(lipgloss.Color("#c8d0dc")).Bold(true).Render("↻" + fmtReset(w.secs))
	} else if w.dur > 0 && w.secs*4 < w.dur {
		reset = lipgloss.NewStyle().Foreground(lipgloss.Color("#c8d0dc")).Render("↻" + fmtReset(w.secs))
	}
	return fmt.Sprintf("  %-9s %s %3d%% used  %s%s", shortWin(w.label), barStr(w.pct), w.pct, reset, note)
}

func (m *model) syncPreview() {
	if !m.rdy || m.collapse {
		return
	}
	var b strings.Builder
	if m.view == pickerView {
		p := m.profiles[m.cursor]
		nm := lipgloss.NewStyle().Foreground(lipgloss.Color(p.color)).Bold(true).Render(p.name)
		b.WriteString(nm + "  " + flavorize(p.blurb) + "\n\n")
		b.WriteString(flavorize(p.detail) + "\n")
		if imp := m.avail.impact(m.routes[p.name]); imp != "" {
			b.WriteString("\n")
			if imp == "broken" {
				b.WriteString(stBrk.Render("✗ "+m.avail.note()+" — default has no live fallback") + "\n")
			} else {
				b.WriteString(stWarn.Render("⚠ "+m.avail.note()+" — runs on a fallback") + "\n")
			}
		}
		b.WriteString("\n" + stDim.Render("── routing ─────────────────") + "\n")
		b.WriteString(renderRoute(m.routes[p.name], m.depth))
	} else {
		id := comboID(m.sel)
		b.WriteString(lipgloss.NewStyle().Bold(true).Render("generated profile") + "\n")
		b.WriteString(stDim.Render(strings.ReplaceAll(id, "_", " ")) + "\n\n")
		if rows, ok := m.generated[id]; ok {
			b.WriteString(stDim.Render("── routing ─────────────────") + "\n")
			b.WriteString(renderRoute(rows, m.depth))
		} else {
			b.WriteString(stDim.Render("no profile for this combination") + "\n")
		}
	}
	// wrap to pane width so a long chain can never shift the layout.
	content := lipgloss.NewStyle().Width(m.vp.Width).Render(b.String())
	m.vp.SetContent(content)
	m.vp.GotoTop()
}

func (m *model) relayout() {
	pw := m.w - m.listW() - 3
	if m.mode() == modeCollapsed {
		pw = m.w
	}
	if pw < 10 {
		pw = 10
	}
	panelH := 0
	if p := m.usagePanel(); p != "" {
		panelH = strings.Count(p, "\n") + 2 // + the rule above the panel
	}
	vh := m.h - 2 - panelH // header + its rule
	if vh < 3 {
		vh = 3
	}
	if !m.rdy {
		m.vp = viewport.New(pw, vh)
		m.rdy = true
	} else {
		m.vp.Width, m.vp.Height = pw, vh
	}
	m.syncPreview()
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.w, m.h = msg.Width, msg.Height
		m.relayout()
	case usageMsg:
		m.avail = availability(msg)
		m.relayout()
	case spinner.TickMsg:
		if !m.avail.ok {
			var cmd tea.Cmd
			m.spin, cmd = m.spin.Update(msg)
			return m, cmd
		}
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "esc", "ctrl+c":
			return m, tea.Quit
		case "tab":
			if m.view == pickerView {
				m.view = genView
			} else {
				m.view = pickerView
			}
			m.syncPreview()
		case "p":
			if m.w >= 62 {
				m.collapse = !m.collapse // hide/show the side preview
			} else {
				m.showResult = !m.showResult // narrow: swap list ↔ result full-screen
			}
			m.relayout()
		case "f":
			m.depth = (m.depth + 1) % 2
			m.syncPreview()
		case "up", "k":
			m.moveUp()
		case "down", "j":
			m.moveDown()
		case "left", "h":
			if m.view == genView {
				m.cycleFacet(-1)
			}
		case "right", "l":
			if m.view == genView {
				m.cycleFacet(1)
			}
		case "enter":
			if m.view == pickerView {
				m.chosen = m.profiles[m.cursor].exe
				return m, tea.Quit
			}
		}
	case tea.MouseMsg:
		switch msg.Button {
		case tea.MouseButtonWheelUp:
			m.vp.LineUp(3)
		case tea.MouseButtonWheelDown:
			m.vp.LineDown(3)
		}
	}
	return m, nil
}

func (m *model) moveUp() {
	stacked := m.mode() == modeStacked
	if m.view == pickerView {
		if m.cursor > 0 {
			m.cursor--
			m.syncPreview()
		} else if stacked { // flow up into the generator
			m.view = genView
			m.fcur = len(m.facets) - 1
			m.syncPreview()
		}
	} else if m.fcur > 0 {
		m.fcur--
	}
}
func (m *model) moveDown() {
	stacked := m.mode() == modeStacked
	if m.view == pickerView {
		if m.cursor < len(m.profiles)-1 {
			m.cursor++
			m.syncPreview()
		}
	} else if m.fcur < len(m.facets)-1 {
		m.fcur++
	} else if stacked { // flow down into the profiles
		m.view = pickerView
		m.syncPreview()
	}
}
func (m *model) cycleFacet(dir int) {
	f := m.facets[m.fcur]
	cur := m.sel[f.key]
	idx := 0
	for i, v := range f.values {
		if v == cur {
			idx = i
		}
	}
	idx = (idx + dir + len(f.values)) % len(f.values)
	m.sel[f.key] = f.values[idx]
	m.syncPreview()
}

func (m model) previewPane() string {
	return lipgloss.NewStyle().
		Border(lipgloss.NormalBorder(), false, false, false, true).
		BorderForeground(lipgloss.Color(cBord)).PaddingLeft(2).
		Width(m.w - m.listW() - 3).Height(m.vp.Height).
		Render(m.vp.View())
}

func (m model) header() string {
	tab := func(label string, on bool) string {
		if on {
			return lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc)).Bold(true).Render(label)
		}
		return stDim.Render(label)
	}
	hint := "tab switch · f depth · p collapse · enter launch · q quit"
	switch m.mode() {
	case modeStacked:
		hint = "tab move focus · f depth · enter launch · q quit"
	case modeCollapsed:
		if m.w < 62 {
			swap := "result"
			if m.showResult {
				swap = "list"
			}
			hint = "tab switch · p " + swap + " · enter launch · q"
		}
	}
	return "  " + tab("profiles", m.view == pickerView) + stDim.Render(" · ") +
		tab("generator", m.view == genView) + stDim.Render("    "+hint)
}

func (m model) View() string {
	if !m.rdy {
		return "loading…"
	}
	var body string
	switch m.mode() {
	case modeStacked:
		sep := stDim.Render(strings.Repeat("─", m.listW()))
		stack := m.genList(m.view == genView) + "\n" + sep + "\n" + m.pickerList(m.view == pickerView)
		left := lipgloss.NewStyle().Width(m.listW()).Render(stack)
		body = lipgloss.JoinHorizontal(lipgloss.Top, left, m.previewPane())
	case modeSplit:
		var l string
		if m.view == pickerView {
			l = m.pickerList(true)
		} else {
			l = m.genList(true)
		}
		body = lipgloss.JoinHorizontal(lipgloss.Top, lipgloss.NewStyle().Width(m.listW()).Render(l), m.previewPane())
	default: // collapsed
		switch {
		case m.showResult && m.w < 62:
			body = m.vp.View()
		case m.view == pickerView:
			body = m.pickerList(true)
		default:
			body = m.genList(true)
		}
	}
	rule := stDim.Render(strings.Repeat("─", m.w))
	out := m.header() + "\n" + rule + "\n" + body
	if foot := m.usagePanel(); foot != "" {
		out += "\n" + rule + "\n" + foot
	}
	return out
}

func (m model) pickerList(focused bool) string {
	trunc := lipgloss.NewStyle().MaxWidth(m.listW()).Inline(true)
	var b strings.Builder
	b.WriteString(sectionTitle("profiles", focused) + "\n\n")
	lastGroup := ""
	for i, p := range m.profiles {
		if p.group != lastGroup {
			b.WriteString(stGrp.Render(p.group) + "\n")
			lastGroup = p.group
		}
		mark := "  "
		switch m.avail.impact(m.routes[p.name]) {
		case "broken":
			mark = stBrk.Render("✗ ")
		case "degraded":
			mark = stWarn.Render("⚠ ")
		}
		nameCol := p.color
		blurb := flavorize(p.blurb)
		if !focused {
			nameCol, blurb = cDim, stDim.Render(p.blurb)
		}
		gly := lipgloss.NewStyle().Foreground(lipgloss.Color(nameCol)).Render(p.glyph)
		nm := lipgloss.NewStyle().Foreground(lipgloss.Color(nameCol)).Bold(focused).Render(p.name)
		row := fmt.Sprintf("%s%s %-6s %s", mark, gly, nm, blurb)
		row = trunc.Render(row)
		if i == m.cursor {
			bg := cSelBg
			if !focused {
				bg = "#141922"
			}
			row = lipgloss.NewStyle().Background(lipgloss.Color(bg)).Width(m.listW()).Render(row)
		}
		b.WriteString(row + "\n")
	}
	return b.String()
}

func sectionTitle(name string, focused bool) string {
	if focused {
		return lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc)).Bold(true).Render("▍ " + name)
	}
	return stDim.Render("  " + name)
}

func (m model) genList(focused bool) string {
	var b strings.Builder
	b.WriteString(sectionTitle("generator", focused) + "\n\n")
	for i, f := range m.facets {
		na := (f.key == "fable" && m.sel["lane"] == "gpt-only") || (f.key == "spark" && m.sel["lane"] == "claude-only")
		onRow := i == m.fcur && focused
		glyCol := laneColor(m.sel["lane"])
		if !focused {
			glyCol = cDim
		}
		gly := lipgloss.NewStyle().Foreground(lipgloss.Color(glyCol)).Render(f.glyph)
		ptr := "  "
		if onRow {
			ptr = lipgloss.NewStyle().Foreground(lipgloss.Color(cAcc)).Render("▸ ")
		}
		row := fmt.Sprintf("%s%s %s", ptr, gly, stDim.Render(pad(f.key, 9)))
		for _, v := range f.values {
			switch {
			case na:
				row += "   " + stDim.Render(v)
			case v == m.sel[f.key]:
				col := cAcc
				if f.key == "lane" {
					col = laneColor(v)
				} else if (f.key == "spark" || f.key == "fable") && v == "on" {
					col = cGreen
				}
				if !focused {
					col = cGrp // grayed but legible when the section is unfocused
				}
				st := lipgloss.NewStyle().Foreground(lipgloss.Color(col)).Bold(focused)
				if onRow { // the cursor sits on the selected value of the focused row
					st = st.Background(lipgloss.Color(cSelBg))
				}
				row += "  " + st.Render(" "+v+" ")
			default:
				row += "   " + stDim.Render(v)
			}
		}
		switch {
		case na:
			row += "   " + stDim.Render("— n/a for this lane")
		case focused && (f.key == "fable" || f.key == "spark") && m.sel[f.key] == "on":
			bkt, lbl := "claude-fable", "Fable"
			if f.key == "spark" {
				bkt, lbl = "codex-spark", "Spark"
			}
			if m.avail.down(bkt) {
				w := lbl + " maxed · " + fmtReset(m.avail.reset[bkt])
				if m.avail.bucket[bkt] == "unauthed" {
					w = lbl + " unavailable"
				}
				row += "   " + stWarn.Render("⚠ "+w+" — no usage left")
			}
		}
		b.WriteString(row + "\n")
	}
	return b.String()
}

func pad(s string, n int) string {
	for len(s) < n {
		s += " "
	}
	return s
}

func main() {
	profiles := loadProfiles(os.Getenv("CODE_PROFILES"))
	if len(profiles) == 0 {
		fmt.Fprintln(os.Stderr, "code: no profiles (CODE_PROFILES)")
		os.Exit(2)
	}
	glyphs := map[string]string{}
	for _, kv := range strings.Split(os.Getenv("CODE_FACET_GLYPHS"), ",") {
		if p := strings.SplitN(kv, "=", 2); len(p) == 2 {
			glyphs[p[0]] = p[1]
		}
	}
	sp := spinner.New()
	sp.Spinner = spinner.Dot
	m := model{
		profiles:  profiles,
		routes:    loadBlocks(os.Getenv("CODE_ROUTES")),
		generated: loadBlocks(os.Getenv("CODE_GENERATED")),
		avail:     availability{bucket: map[string]string{}, reset: map[string]int64{}},
		usageCmd:  os.Getenv("CODE_USAGE"),
		spin:      sp,
		glyphs:    glyphs,
		view:      genView, // generator is the default view
		facets:    facetDefs(glyphs),
		sel:       map[string]string{"lane": "mixed", "model": "normal", "thinking": "medium", "spark": "on", "fable": "off"},
	}
	final, err := tea.NewProgram(m, tea.WithAltScreen(), tea.WithMouseCellMotion()).Run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	if fm, ok := final.(model); ok && fm.chosen != "" {
		args := append([]string{fm.chosen}, os.Args[1:]...)
		if err := syscall.Exec(fm.chosen, args, os.Environ()); err != nil {
			fmt.Fprintln(os.Stderr, "code: exec:", err)
			os.Exit(1)
		}
	}
}
